* 深澤諭史弁護士の「弁護士全体を逆恨み」，と広島の原爆投下を描いた漫画「はだしのゲン」
  :LOGBOOK:
  CLOCK: [2020-08-06 木 09:43]--[2020-08-06 木 11:57] =>  2:14
  :END:

:CATEGORIES: 深澤諭史弁護士,漫画,弁護士

〉〉〉：Emacs： 2020-08-06（木曜日）09：43　 〉〉〉

　さきほどTwitterのタイムラインに「はだしのゲン」を見つけ，いくつかツイートを読んだ後，作者について調べてみました。2012年12月に亡くなっていたことをしったのですが，顔写真を見ても，見覚えがあるとは思えませんでした。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 09:46／2020/08/06 09:37 URL： https://twitter.com/kk_hirono/status/1291173819491799044 https://twitter.com/hirono_hideki/status/1291171540667596803  

> 漫画家の中沢啓治さん死去　「はだしのゲン」作者: 日本経済新聞 https://t.co/XNwI96X1oh  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 09:46／2020/08/06 09:31 URL： https://twitter.com/kk_hirono/status/1291173892472614912 https://twitter.com/hirono_hideki/status/1291170091216842757  

> はだしのゲン - Twitter検索 / Twitter https://t.co/ItXkKZ8MR3  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 09:47／2020/08/06 08:20 URL： https://twitter.com/kk_hirono/status/1291173925859348481 https://twitter.com/hirono_hideki/status/1291152229177540609  

> 2020年08月06日08時19分の登録： REGEXP：”逆恨み”／深澤諭史（@fukazawas）の検索（2014-09-22〜2020-08-05／2020年08月06日08時19分の記録55件） https://t.co/aPdVQASQOg  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 09:47／2020/08/06 08:20 URL： https://twitter.com/kk_hirono/status/1291173941017546754 https://twitter.com/hirono_hideki/status/1291152202766008322  

> 2020年08月06日08時17分の登録： REGEXP：”逆恨み”／データベース登録済みツイート：2020年08月06日08時11分の記録：ユーザ・投稿：154／430件 https://t.co/z3XUcfI96L  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 09:47／2020/08/06 08:20 URL： https://twitter.com/kk_hirono/status/1291174046734987269 https://twitter.com/hirono_hideki/status/1291152176430030848  

> 2020年08月06日07時58分の登録： REGEXP：”井戸謙一”／データベース登録済みツイート：2020年08月06日07時56分の記録：ユーザ・投稿：49／171件 https://t.co/auvk5Ycpso  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 09:47／2020/08/06 08:20 URL： https://twitter.com/kk_hirono/status/1291174056323153920 https://twitter.com/hirono_hideki/status/1291152150089801728  

> 2020年08月06日07時52分の登録： ＼郷原信郎【「深層」カルロス・ゴーンとの対話　起訴されれば９９％超が有罪となる国で】　@nobuogohara＼ツイートで私が吉村知事自身の発言を引用して批判しているのに https://t.co/1Ti8V0SIdB  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 09:47／2020/08/06 08:20 URL： https://twitter.com/kk_hirono/status/1291174069522567174 https://twitter.com/hirono_hideki/status/1291152123619692544  

> 2020年08月06日07時50分の登録： ＼Shoko Egawa　@amneris84＼自治体が法的根拠がないままに、それぞれの緊急事態宣言を出さざるを得ない状況になっているのに、国はどうするつもりだろう。その https://t.co/SjiMn7PdAk  

```
1966年に母を原爆症で亡くしたことを契機に、原爆をテーマにした作品の執筆を決意。68年、「黒い雨にうたれて」を発表し、73年に「はだしのゲン」の連載を週刊少年ジャンプで開始した。「はだしのゲン」は英語やロシア語など翻訳中を含めて18カ国語に訳され、総発行部数は1千万部を超える。

［source：］漫画家の中沢啓治さん死去　「はだしのゲン」作者： 日本経済新聞 https://r.nikkei.com/article/DGXNASDG25016_V21C12A2CC0000?s=5
```

　上記の記事に「はだしのゲン」の週刊少年ジャンプの連載が昭和48年から始まったとあるのですが，私の記憶では昭和50年4月に辺田の浜から宇出津の小棚木に引っ越した後のことになります。

　一つの傾向ですが，辺田の浜に住んでいる頃は，週刊少年チャンピオンと週刊少年マガジンをよく読んでいて，宇出津の小棚木に来てからは週刊少年ジャンプを読むことが多かったと思います。

　辺田の浜に住んでいる頃に，週刊少年ジャンプの連載として印象にあるのは「トイレット博士」でした。その漫画の内容が徐々に変化し，メタクソ団として活動をするようになった時期が，小棚木に来てからのことで，同じジャンプの「はだしのゲン」の連載と重なります。

　メタクソ団の活動は，そのしばらくあとと思うのですが，これも週刊少年ジャンプの連載で「東大一直線」の展開に重なるところがありました。主人公の東大通が東大つまり東京大学に合格，入学，活躍という展開です。この活躍の頃に週刊少年ジャンプは読まなくなりました。

　「トイレット博士」と「東大一直線」は，そのまま深澤諭史弁護士の弁護士としての活躍に重なるところがあると常々考えてきました。昨日も思っていたのですが，漫画家が思い描いた人生を自ら演じるあるいは実践するという感じです。それが現実問題という検討課題でもあります。

@fukazawas ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@fukazawas）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW fukazawas（深澤諭史） 日時：2020/08/05 16:14 URL： https://twitter.com/fukazawas/status/1290908992433041408  

> たまに、こういう、弁護士全体を逆恨みしているみたいな人には遭遇しますね。相談者にもいますし、ネットにはもっといっぱいいます。  
> 属性は統一できないが、クレーマー、ストーカー、DV加害者、モラハラ加害者は弁護士全般への憎悪が強い傾向を… https://t.co/CkxRVLYHNS  

　今確認すると昨日の16時14分が投稿時刻となっていますが，けっこう衝撃的なツイートでした。弁護士による悪夢，それが本件告発事件の実質的な内容でもあるのですが，走馬灯となって各場面が目まぐるしく思い出されました。

　これは今に始まったことではなく，最近は見かけていないですが，深澤諭史弁護士のツイートには「はだしのゲン」に対する格別な思い入れもあるらしく，披瀝がありました。だいたいは町内会長の話となっていました。

　そんなに数はないと思うので，深澤諭史弁護士に限らず，「はだしのゲン」をキーワードに含み記録したデータを次にご紹介します。

```
(py37_env) a66@a66-XTe:~$ dp -p|grep はだしのゲン
 - 2017年11月11日21時09分の登録： ＼いわぽん　@yiwapon　RT：　@fukazawas＼「はだしのゲンの町内会長」現象として，数年前から予言しています。 \n （・∀・） http://hirono2014sk.blogspot.com/2017/11/yiwaponrtfukazawas.html
 - 2018年01月31日11時54分の登録： REGEXP：”はだしのゲンの町内会長”／データベース登録済みツイート：2018年01月31日11時53分の記録：ユーザ・投稿：13／32件 http://hirono2014sk.blogspot.com/2018/01/regexp2018013111531332.html
 - 2018年03月15日10時12分の登録： ＼深澤諭史　@fukazawas＼テレビを付けていたら，はだしのゲンが実写化されて，町内会長の登場シーンかな？っておもったら，ただのニュースだった。 紛らわしいな（・∀・ http://hirono2014sk.blogspot.com/2018/03/fukazawas_25.html
 - 2018年06月02日05時41分の登録： REGEXP：”弁護士の魅力を伝えるためにはだしのゲンの雑コラ作り”／データベース登録済みツイート：2018年06月02日05時40分の記録：ユーザ・投稿：33／33件 http://hirono2014sk.blogspot.com/2018/06/regexp2018060205403333.html
 - 2018年12月09日11時24分の登録： REGEXP：”はだしのゲン”／深澤諭史（@fukazawas）の検索（2015-06-05〜2018-12-09／2018年12月09日11時23分の記録44件） http://hirono2014sk.blogspot.com/2018/12/regexpfukazawas2015-06-052018-12.html
 - 2019年03月02日23時13分の登録： ＼リーチ一発ツモ裏１　@luckymangan＼「実は」反対なんて言ってる輩ははだしのゲンの町内会長だろ。本当に反対の人はハナから反対と言ってる。 http://hirono2014sk.blogspot.com/2019/03/luckymangan.html
 - 2019年07月28日17時56分の登録： ＼弁護士7286　@jmjhjmwtad＼Twitter のイキリ弁護士のイキリ芸、はだしのゲン1巻のゲンと弟の「八百余州の乞食ーデンデン」みたいな乞食芸なんで、売上が殆 http://hirono2014sk.blogspot.com/2019/07/7286jmjhjmwtadtwitter-1.html
 - 2019年08月19日16時06分の登録： REGEXP：”はだしのゲンの町内会長”／データベース登録済みツイート：2019年08月19日16時05分の記録：ユーザ・投稿：15／47件 http://hirono2014sk.blogspot.com/2019/08/regexp2019081916051547.html
 - 2019年10月05日16時38分の登録： ％@fukazawas　深澤諭史％ＲＴ\n全てが終わった後に，はだしのゲンの町内会長みたいなのがたくさん現れることを予想している。\nまあ，すでに準備を始めている人もいますが。\n(･∀･) http://hirono2014sk.blogspot.com/2019/10/fukazawasnnn.html
 - 2019年10月05日16時39分の登録： ％@fukazawas　深澤諭史％法科大学院制度についても，同じようなことが起こりそうだな。\n\nいや，もう起こりつつあるか。未来のはだしのゲンの町内会長みたいなのが一杯出てきそうだ。 http://hirono2014sk.blogspot.com/2019/10/fukazawasnn.html
 - 2019年10月05日16時39分の登録： ％@fukazawas　深澤諭史％大昔に「はだしのゲン」を読んだとき「昔の日本には，こんな時代があったのか。もう二度と無いだろうし，あってはならないけれど，酷い時代もあっ http://hirono2014sk.blogspot.com/2019/10/fukazawas_26.html
 - 2019年10月05日16時39分の登録： ％@fukazawas　深澤諭史％＞ＲＴｓ\nロー制度は，いまでもそうだけれども，今後ますます，はだしのゲンの町内会長みたいなのが大量発生すると思う http://hirono2014sk.blogspot.com/2019/10/fukazawasn.html
 - 2019年10月05日16時40分の登録： ％@fukazawas　深澤諭史％>RTs\n以前，予言？したとおり，本当に，はだしのゲンの町内会長現象が起きているのかもしれない。 http://hirono2014sk.blogspot.com/2019/10/fukazawasrtsn.html
 - 2019年10月05日16時40分の登録： ％@fukazawas　深澤諭史％司法改革の戦犯が誰かなんて，あんまり興味は無いなぁ・・。\nＡ級戦犯より，むしろ，はだしのゲンの町内会長みたいな人がちらほらと。\n（・∀・） http://hirono2014sk.blogspot.com/2019/10/fukazawasnn_5.html
 - 2019年10月05日16時41分の登録： ％@fukazawas　深澤諭史％（；＾ω＾）（利権・ポストはもらったが）俺も大変だったお\n（・∀・）お前は，はだしのゲンの町内会長か http://hirono2014sk.blogspot.com/2019/10/fukazawasn_5.html
 - 2019年10月05日16時41分の登録： ％@fukazawas　深澤諭史％「はだしのゲンの町内会長」現象として，数年前から予言しています。\n（・∀・）https:// http://hirono2014sk.blogspot.com/2019/10/fukazawasnhttps.html
 - 2019年10月05日16時41分の登録： ％@fukazawas　深澤諭史％（＃＾ω＾）（俺様の賃金はもちろん保障されているが）赤字だから利権じゃないんだお！\n（・∀・）お前らは，はだしのゲンの町内会長か。#司法改革コント http://hirono2014sk.blogspot.com/2019/10/fukazawasn_92.html
 - 2019年10月05日16時42分の登録： ％@fukazawas　深澤諭史％まさに「はだしのゲンの町内会長」みたいですね。 http://hirono2014sk.blogspot.com/2019/10/fukazawas_15.html
 - 2019年10月05日16時42分の登録： ％@fukazawas　深澤諭史％はだしのゲンの町内会長現象として予言しています。\n（・∀・）\n（；＾ω＾）（利権・ポストはゲットしたけれども）実は，私は，昔から反対 http://hirono2014sk.blogspot.com/2019/10/fukazawasnn_66.html
 - 2019年10月05日16時42分の登録： ％@fukazawas　深澤諭史％昔，「はだしのゲン」を読んだとき，そこに出てくる町内会長の変節ぶりが，いかにも漫画的な表現だなぁって，おもったけれども。\nまさか，平成の世に，同じ光景を目の当たりにするとは。\n（・∀・；） http://hirono2014sk.blogspot.com/2019/10/fukazawasnn_24.html
 - 2019年10月05日16時43分の登録： ％@fukazawas　深澤諭史％オウム真理教の件については、はだしのゲンの町内会長みたいな立場ですよね、テレビって。\n選挙に出て敗北して…、と、その「前」があったでしょう？\n忘れたとは言わせない。\n（・∀・） http://hirono2014sk.blogspot.com/2019/10/fukazawasnnn_5.html
 - 2019年10月05日16時43分の登録： ％@fukazawas　深澤諭史％美しい国の伝統「はだしのゲンの町内会長現象」  http://hirono2014sk.blogspot.com/2019/10/fukazawas_9.html
 - 2020年03月31日22時39分の登録： ＼7286　@jmjhjmwtad＼しかし、同業者からリアルはだしのゲン町内会長が出るとは。後で「私は自粛には反対だったんだ」みたいなこと言い出すかもね。 http://hirono2014sk.blogspot.com/2020/03/7286jmjhjmwtad_31.html
 - 2020年04月11日23時55分の登録： REGEXP：”はだしのゲン”／深澤諭史（@fukazawas）の検索（2015-06-05〜2019-10-14／2020年04月11日23時55分の記録49件） http://hirono2014sk.blogspot.com/2020/04/regexpfukazawas2015-06-052019-10.html
 - 2020年05月10日14時59分の登録： ＼弁護士足立敬太 @アレクサ 六甲おろしかけて　@keita_adachi＼はだしのゲンは日本人の恐ろしさをよく表現した漫画だったね。 子供ながら怖い怖いと思いながら読ん http://hirono2014sk.blogspot.com/2020/05/keitaadachi.html
```

　深澤諭史弁護士のツイートには，逆恨みにも関連して「病院」，「治療」というキーワードがしばしば出てくるのですが，上記のデータベースの検索結果を見ながら思い出したニュースがありました。昨夜の「ニュースいしかわ８４５」だったと思います。

　民事裁判の控訴審のニュースでしたが，そういえば病院名が出ていなかったような気がしました。これで３回目か４回目になるのですが，いずれもテレビの石川県内ニュースとしてのみみてきたものです。

金沢地方裁判所　控訴 - Google 検索 https://t.co/kal5BDypEh

身体拘束後に死亡　控訴審始まる｜NHK 石川県のニュース https://t.co/pQVu13dw6z

　Googleの検索は，「金沢地方裁判所　控訴」をキーワードに，２４時間以内のオプション指定をしました。該当があったのは１ページめのみの確認ですが，１番目の１件だけです。「NHK石川のニュース」とあります。

```
４年前、石川県内の病院の精神科に入院した４０歳の男性が、体をベッドに拘束されたあと、エコノミークラス症候群を発症して死亡したのは、必要性がない身体拘束が原因だとして、両親が賠償を求めた裁判の２審の審理が名古屋高等裁判所金沢支部で始まり、原告の両親は訴えを退けた１審判決を強く批判しました。

［source：］身体拘束後に死亡　控訴審始まる｜NHK 石川県のニュース https://www3.nhk.or.jp/lnews/kanazawa/20200806/3020005663.html
```

　昨夜テレビで見たのと同じ内容と思いましたが，「石川県内の病院の精神科」とあるだけで病院名はありません。前の裁判のニュースは病院名が出ていましたし，映像もあったかもしれません。

　上記の記事には動画のニュースが付いているのですが，アナウンサーが余り見ない顔で，スタジオの背景が淡い赤茶色に見えるのも見覚えのないものです。記事は本日８月６日で８時４０分とあります。朝に放送されたテレビニュースになるのかもしれません。

　録画していた番組で確認したのですが，アナウンサーは記事にある動画と同じ人のようです。船岡久嗣と名前がでています。スタジオの背景の模様も同じにみえますが，テレビの方が水色に見えます。ニュースいしかわ８４５では，ニュース項目の一覧も出ていません。

　病院の名前で検索したのですが，裁判に関する情報は出てきませんでした。Googleマップで病院名を調べると普通に情報が出てきたので，病院名が間違っていないことは確認しました。・・・と，ここで，間違いに気がついたのですが，「24時間以内」のオプションを付けたままでした。

```
秋山晴康｜2020年3月3日7：27PM

精神科病院へ入院中の大畠一也さんが亡くなったのは病院の不当な身体拘束が原因であるとして、両親が病院を経営する社会福祉法人金沢市民生協会（石川県野々市市、片岡正子理事長）に約８６３０万円の損害賠償を求めた訴訟の判決で、金沢地裁（押野純裁判長）は１月31日、原告の訴えを棄却した（事件の詳細は、本誌１月31日号に掲載）。２０１６年12月、一也さん（当時40歳）は入院先の「ときわ病院」のベッドで６日間身体拘束を受けたうえ、下肢深部静脈血栓による肺動脈血栓塞栓症、すなわちいわゆるエコノミークラス症候群で死亡した。

［source：］「身体拘束され死亡」　遺族が病院提訴も棄却　金沢地裁 ｜ 週刊金曜日オンライン http://www.kinyobi.co.jp/kinyobinews/2020/03/03/antena-661/
```

　週刊金曜日という雑誌は，だいぶん前から情報を見かけていますが，全国紙なのかは不明です。石川県だけなら北國新聞社の「アクタス」になりますが，そういうことはないはずです。週刊金曜日オンラインとあるので，やはり出版もされているのでしょう。宇出津の書店にはなさそうですが。

提訴：「不当拘束」　遺族が精神科病院を - 毎日新聞 https://t.co/sLniXvJPCl

　上記の記事にある「運営する社会福祉法人「金沢市民生協会」」というのは覚えになく，聞いた覚えがないのですが，「ときわ病院」については，以前に時間を掛けて調べました。

　金沢市の卯辰山にあった医療施設が始まりらしく，それがハンセン病の隔離の問題とも重なるものに感じられました。「ときわ病院」の所在地となっている場所は，以前，よく通っていると思うので，病院の建物は見ていたような気もするのですが，そこに精神病院があるとは知らなかったです。

　NHK石川の記事の動画と，昨夜のニュースいしかわ８４５の放送内容は同じだと思います。テーブルの向かって左側3人がご遺族のようですが，右手に二人，弁護士と思われる人物がいて，どちらも弁護士バッチが見えないのが気になりました。

　この「ときわ病院」の訴訟ですが，被告発人木梨松嗣弁護士，被告発人小島裕史裁判長に共通した犯罪性とも関連があると考えていました。そのうちすっかり忘れていたのですが，昨夜のテレビで思い出すことができました。

　NHKのニュースいしかわ８４５ですが，最近はだいたい3,4日に1回のペースで視聴をしていると思います。見ない方が多いので，見落とし，見逃しの可能性もあったわけです。いちおう毎回録画予約をしているのですが，普通に再生することはありません。

　昨日は7月31日に気になるニュースを見つけ，レコーダーの録画一覧を見たのですが，ちょうど7月31日で録画が途切れていました。ディスク容量がいっぱいになったためで，削除で容量をあけました。

　そのついでになったのですが，だいぶん前に録画したまま視聴していなかった番組があり，多少，石川県のかほく市とも関わりがあるのですが，オウム真理教の井上嘉浩元死刑囚の番組でした。井上嘉浩元死刑囚の父親とかほく市の住職の話がメインの番組でした。

　他の石川県内の番組でも，かほく市の住職と井上嘉浩元死刑囚の関係はみていたのですが，京都の仏教系の学校の同窓生で，住職の方が５つ年上，京都からかほく市に来て住職になったということは，その番組で初めて知りました。

　時刻は11時23分です。深澤諭史弁護士のタイムラインの更新を確認したところ，気になるリツイートがあったのですが，少し下に下げると，19時間前として自身のツイートのリツイートが出てきました。「弁護士全体を逆恨み」という本項でメインのツイートです。

@popohito ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@popohito）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW popohito（ぽぽひと@睡眠重視） 日時：2020/08/06 09:05 URL： https://twitter.com/popohito/status/1291163338379005957  

> こういうのは「主語がでかい」って突っ込まれないのかね。 https://t.co/luTK0Q7ylR  

　深澤諭史弁護士のタイムラインでよく見かけるアカウントですが，ブロックされているのか覚えておらず，リツイートを試みたところブロックされていることを確認しました。この「主語がでかい」というツイートは，次のツイートを引用リツイートしたもので，そちらの画像が目立っています。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜nippon_no_tsuki（かしたん） 日時：2020-08-06 11:28／2020/08/06 06:44 URL： https://twitter.com/kk_hirono/status/1291199412689965056 https://twitter.com/nippon_no_tsuki/status/1291127873651105792  

> 広島市民の願いはこれです。  京都や沖縄や県外から来て、原爆とは関係ない話を拡声器で喋って騒いで欲しい訳がない。 https://t.co/ppFecg81VE  

　「弁護士全体を逆恨み」の下にあるのも気になる内容のツイートでした。みかけないプロフィールの名前で，一般のアカウントと思ったのですが，プロフィールに弁護士とありました。

　リストには未登録でした。プロフィールの内容は以前に見かけていたような気がしていたのですが，似たような内容というのはあるかもしれません。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜5ByiYMhnN2468ho（少数意見のひとりごと） 
日時：2020-08-06 11:32／2020/08/05 20:54 URL： https://twitter.com/kk_hirono/status/1291200542954250241 https://twitter.com/5ByiYMhnN2468ho/status/1290979444614549506  

> 地雷依頼者の見分け方　②調子のいいことを言う　初対面で「素晴らしい先生に出会った」とか，調子のいいことをいう人は要注意。あなたが素晴らしい弁護士であるからではなく，もともと，弁護士に対する期待値が高いから調子のいいことを言う。しかし，期待が裏切られると，クレーマーに変身する。  

```
少数意見のひとりごと
@5ByiYMhnN2468ho
自然をこよなく愛する田舎の弁護士。自分の意見は，どちらかというと，少数派という自覚はありますが，論理的におかしいことはおかしいと言いたくなる。クソリプへの有効な反論は、スルーと気づいた。
2020年5月からTwitterを利用しています
484 フォロー中
207 フォロワー

［source：］(5) 少数意見のひとりごとさん (@5ByiYMhnN2468ho) / Twitter https://twitter.com/5ByiYMhnN2468ho
```

　アカウントのヘッダ画像に朱色の吊橋が出てきたのですが，これは見たことがあると思いました。わりと最近で，見かけた回数は1,2回と思います。宇出津の遠島山公園にあるしらさぎ橋とも似ているので印象に残っていました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 
日時：2020-08-06 11:42／2020/08/06 11:35 URL： https://twitter.com/kk_hirono/status/1291202916200534016

 https://twitter.com/s_hirono/status/1291201174083796992  

> 2020-08-06-113406_少数意見のひとりごとさん　（@5ByiYMhnN2468ho）　／　Twitter.jpg https://t.co/gks8LMX4r7  

```
地雷依頼者の見分け方　③事案の緊急性を強調する。事案について，いかに緊急であるかを強調する。しかし，実際は，事案が緊急であるわけではなく，相談者にとって緊急なだけ。すなわち，相談者のキャパの小ささが，事案を緊急に感じさせている。キャパの小ささは，そのまま弁護士に対するクレームへ。
```

　上記の内容のツイートのリツイートができず，速攻でブロックされたのかと思ったのですが，その様子はなく，自分のアカウントの方で投稿制限が掛かったようにも思え，結局，ページの再読込をすると，「このアカウントは存在しません」と出ました。

〈〈〈：Emacs： 2020-08-06（木曜日）11：57 　〈〈〈

* 

