* 大量不当懲戒請求のカンパ，嶋﨑量弁護士とは別，北周士弁護士と佐々木亮弁護士の振込口座が一緒になっていた，嶋﨑量弁護士と佐々木亮弁護士のツイートの記録
  :LOGBOOK:
  CLOCK: [2020-08-01 土 00:33]
  :END:

:CATEGORIES: 懲戒請求,北周士弁護士,嶋﨑量弁護士,佐々木亮弁護士,カンパ

〉〉〉：Emacs： 2020-08-01（土曜日）00：33　 〉〉〉

```
➜  ~ ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb shima_chikara 'カンパ' '1000-01-01/3000-01-01'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1000-01-01' AND '3000-01-01' AND (user LIKE "shima_chikara") AND  tweet REGEXP "カンパ"  ORDER BY tw_date ASC
REGEXP：”カンパ”／嶋﨑量（弁護士）（@shima_chikara）の検索（2018-05-09〜2020-03-13／2020年08月01日00時18分の記録45件）
➜  ~ ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb ssk_ryo 'カンパ' '1000-01-01/3000-01-01'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1000-01-01' AND '3000-01-01' AND (user LIKE "ssk_ryo") AND  tweet REGEXP "カンパ"  ORDER BY tw_date ASC
REGEXP：”カンパ”／ささきりょう（@ssk_ryo）の検索（2011-08-06〜2020-05-23／2020年08月01日00時26分の記録26件）
```

　面倒だったのですが，北周士弁護士とは違い，嶋﨑量弁護士と佐々木亮弁護士のツイートは，同じカンパをキーワードにしたTwitter検索から全てのツイートをデータベースに登録する作業を行い，そのデータベースに基づくまとめ記事を作成，投稿しました。

　何度かご紹介していると思いますが，まとめ記事の作成と投稿は，1つの自作コマンド（スクリプト）で実行しています。以前は，Twitter検索のソースからツイートのURLをスクレイピングの処理で一度に取得できたのですが，それが困難となって手作業となっています。

 - 2020年08月01日00時18分の登録： REGEXP：”カンパ”／嶋﨑量（弁護士）（@shima_chikara）の検索（2018-05-09〜2020-03-13／2020年08月01日00時18分の記録45件） http://hirono2014sk.blogspot.com/2020/08/regexpshimachikara2018-05-092020-03.html

　まずは嶋﨑量弁護士のツイートです。まとめ記事を時系列で見ながら，これはと思うツイートに絞ってリツイートをしていきたいと思います。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:42／2018/05/09 17:53 URL： https://twitter.com/kk_hirono/status/1289224972850720768 https://twitter.com/shima_chikara/status/994138178842906624  

> 私もカンパしました（笑） https://t.co/y4eE6f1oLr  

　すでにリツイート済みですが，上記の1番目になる嶋﨑量弁護士のツイートは，次の北周士弁護士のツイートを引用リツイートしたものになります。嶋﨑量弁護士のツイートは2018年5月9日，北周士弁護士のツイートは同年4月27日となっています。

- TW noooooooorth（ノ ー ス ラ イ ム） 日時： 2018/04/27 17:19 URL： https://twitter.com/noooooooorth/status/989781133880582144  

> #不当懲戒 に対応するための費用のカンパをお願いするための口座を作成しました。本件では今後懲戒請求者等に対し民事・刑事上の責任を追及していく予定ですが相応の費用がかかります。少しでも皆さまのお力添えを頂けますと幸いです。 https://t.co/XvxFh3Gor9  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:46／2018/05/10 21:07 URL： https://twitter.com/kk_hirono/status/1289225972810539009 https://twitter.com/shima_chikara/status/994549570326556672  

> 「佐々木弁護士は･･･『請求に基づく弁護士会の調査を受けており、本業に物理的な支障が出ている。気味が悪く、精神的な苦痛も味わった』と話す。２人は全請求者に損賠賠償請求訴訟を起こし、虚偽告訴罪や業務妨害罪での刑事告訴も検討･･･カンパも募り、すでに５００万円近い提訴資金を集めた」  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:46／2018/05/10 21:05 URL： https://twitter.com/kk_hirono/status/1289226028162748416 https://twitter.com/shima_chikara/status/994549073595191297  

> 社会問題となりつつあるようですね。 ⇒　弁護士：大量「懲戒請求」返り討ち　賠償請求や刑事告訴も - 毎日新聞 https://t.co/5zzPz89U72  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:47／2018/05/12 11:10 URL： https://twitter.com/kk_hirono/status/1289226151269867523 https://twitter.com/shima_chikara/status/995124076791255041  

> #不当懲戒請求 への法的措置をとるか否かの主たる考慮要素は、既存の依頼者や活動への影響。そこを克服するのは、頼りになる同僚含む仲間であり、最後は「お金」。相当額の実費もかかるし、手間暇はお金で買えるので影響を最小限にできる。 それで、カンパに頼ることにしました（現在口座開設中）。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:47／2018/05/12 11:15 URL： https://twitter.com/kk_hirono/status/1289226203786694656 https://twitter.com/shima_chikara/status/995125385175052288  

> 全国にいる仲間の存在は大きい。私の懲戒請求書は肩書きで「日本労働弁護団事務局長」とあった。私は昨年11月まで日本労働弁護団（1700名）の事務局長の仕事を活動の中心にしていた。労働運動で志を同じくする弁護士が全国にいるのでご助力をお願いする予定。その際カンパを活用したい。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:48／2018/05/15 12:04 URL： https://twitter.com/kk_hirono/status/1289226425774432258 https://twitter.com/shima_chikara/status/996224737247350785  

> 現在、私に対し591件の懲戒請求があり、同種被害状況等から全体で960件の懲戒請求があるようです。 被告数600人・請求額1人30万円でも、郵券・印紙代だけで300万を超える実費が予想されます。カンパは、主にこの民事訴訟の実費（郵券・印紙代）として使用を予定しております。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:48／2018/05/15 12:06 URL： https://twitter.com/kk_hirono/status/1289226498709192704 https://twitter.com/shima_chikara/status/996225185022857216  

> 使用内容につきましては、TwitterやFacebook等で報告させていただきます。 カンパに余剰が生じた場合、同様の被害にあった弁護士のため活用させていただく予定で、引継先等も同様にご報告します。 皆さまのお力添えを頂戴できますと幸いです。何とぞよろしくお願い致します。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:48／2018/05/16 14:57 URL： https://twitter.com/kk_hirono/status/1289226557882372096 https://twitter.com/shima_chikara/status/996630661439021056  

> 昨日開始したカンパ、１日で１０６件８６万７６０９円集まりました。ありがとうございます！ 個別返信が追いつかず漏れている方、申し訳ありません。 金額もですが、100人以上が支援してくれていることが、力になります。 お金が集まれば取れ… https://t.co/kUR2CxW3Sc  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:49／2018/05/16 15:00 URL： https://twitter.com/kk_hirono/status/1289226642598924288 https://twitter.com/shima_chikara/status/996631568549535744  

> カンパ大喜利というより、昔のご依頼者や、お付合いのある組合関係者や研究者、あとは直接のご面識もない弁護士さんが多いです。Twitterでの告知をみていただいた方だろう。ありがとうございますm(__)m  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:49／2018/05/16 15:19 URL： https://twitter.com/kk_hirono/status/1289226722940919809 https://twitter.com/shima_chikara/status/996636298143137793  

> 一番強力なカンパは、アマテラスオオミカミ　様、これ最強。ツタンカーメン　様も多分強い。 アンパンマン　様も強いが、ジャムおじさんの助けがないと心細いか？乞うご期待。 とはいえ、タサキ　スシロー　様もいれば、チェゲバラ　様もいるから、メンバーは多彩。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:49／2018/05/17 19:56 URL： https://twitter.com/kk_hirono/status/1289226782143471616 https://twitter.com/shima_chikara/status/997068321563422721  

> 本日15時時点で187名から129万8152円ものカンパをいただきました。ありがとうございますm(__)m 引き続き、宜しくお願いします。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:50／2018/05/19 00:39 URL： https://twitter.com/kk_hirono/status/1289226847989796865 https://twitter.com/shima_chikara/status/997501904006533120  

> #高プロ強行採決 もピンチだし、#不当懲戒 で煩わしいが、今日は良いことも。 カンパを直接事務所に届け応援メッセージくれた方が二人。１人は遠路はるばるTwitterみてお仕事の合間に、もうお１人は担当する争議当事者。多くの方のカン… https://t.co/ko9JPVZglO  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:50／2018/05/21 23:03 URL： https://twitter.com/kk_hirono/status/1289226934514155520 https://twitter.com/shima_chikara/status/998564879714811904  

> 本日15時時点で、271人から201万8401円のカンパをいただきました。本当にありがとうございますm(__)m メンバーも多彩。ウヨクン　様とか、アベアキエイノリマス　さんとか。グンマチャンもありがとう。そして、沢山の法クラの皆… https://t.co/e4XhCpRKRg  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:50／2018/05/24 08:21 URL： https://twitter.com/kk_hirono/status/1289226999160901632 https://twitter.com/shima_chikara/status/999430264462848000  

> 本当にそのとおり。 ノースライム先生や私など被害を受けた弁護士の被害回復に向けた法的措置が、結果として、懲戒制度の健全化に向けた動きにも資するなら、やり甲斐もあるます。 弁護士や弁護士の活動に賛意を示す多くの方からのカンパは、これ… https://t.co/z98sTl3yTg  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:50／2018/05/30 23:36 URL： https://twitter.com/kk_hirono/status/1289227061274398720 https://twitter.com/shima_chikara/status/1001834654624722944  

> 本日30日時点で326人の方から251万7369円のカンパをいただきました。ありがとうございますm(__)m 昔のご依頼者とか、前の職場の関係者とか。長らくお目にかかっていない方々、個別にご挨拶できず申し訳ありません。 現依頼者や… https://t.co/oq99GlJxE7  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:51／2018/05/30 23:42 URL： https://twitter.com/kk_hirono/status/1289227122435710976 https://twitter.com/shima_chikara/status/1001836198376030208  

> 現在、カンパ募集はネット上だけやっているのですが、弁護士になる前の知人、長らくお目にかかっていない方からも沢山カンパをいただき、本当に嬉しいです。 あと、みんなTwitterみてくれてたんだな・・というが分かったのは驚きでした。感謝。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:51／2018/05/30 23:45 URL： https://twitter.com/kk_hirono/status/1289227248231256065 https://twitter.com/shima_chikara/status/1001837074805223424  

> 司法試験に受かる前後、司法修習生になるまで、伊藤塾で講師やゼミなど長らく担当していたのですが、そのときのゼミ生など沢山カンパをしてくれてます。 お会いする機会も無い方ばかりだし、そもそも匿名で当時のゼミ名などで送金して下さる方も多く、御礼もできないのですが、本当に感謝。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:52／2018/06/06 09:49 URL： https://twitter.com/kk_hirono/status/1289227455106965507 https://twitter.com/shima_chikara/status/1004163328627732480  

> 大量不当懲戒請求への法的措置のためカンパ募集したら「恐ろしいビジネスモデル」だとの理由で、新たに懲戒請求されました。 折角なので。原因となったカンパはまだまだ募集してますので、宜しくお願いしますm(__)m ◆みずほ銀行　横浜支店… https://t.co/z8w9sjnfJW  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:52／2018/06/06 10:56 URL： https://twitter.com/kk_hirono/status/1289227545188032513 https://twitter.com/shima_chikara/status/1004180074873085952  

> 本日時点で、336人から約254万円のカンパをいただきました。どうもありがとうございますm(__)m　 人数ベースで5分1くらいは、弁護士の方からのカンパと思われます。金額ベースだともっと割合は高くなります。 法クラの皆さまに感謝。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:53／2018/07/12 18:53 URL： https://twitter.com/kk_hirono/status/1289227625366347776 https://twitter.com/shima_chikara/status/1017346173521178624  

> 先ほどまで、佐々木・北弁護士と大量懲戒請求の弁護団会議。諸事情により提訴が予定より遅れてますが準備進めてます（カンパいただいた方、申し訳ありません）。 まずは、佐々木・北弁護士の提訴が先発となりますが、私の分も提訴します。強力な弁護団も助力いただいており、心強いです。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:53／2018/07/14 07:54 URL： https://twitter.com/kk_hirono/status/1289227668181798913 https://twitter.com/shima_chikara/status/1017905176353443841  

> カンパをお願いしてるときにお約束している通り、刑事もやります。 https://t.co/GXiYmuR5LQ  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:53／2018/08/27 23:32 URL： https://twitter.com/kk_hirono/status/1289227759995117570 https://twitter.com/shima_chikara/status/1034086251463233536  

> これで、私宛計958件の扇動された懲戒請求が確定し、請求者も全て特定済み。 提訴できる環境がほぼ整ったので、カンパしていただいた皆さま、もう少しお待ちくださいm(__)m 訴状は、佐々木・北弁護士と協働でほぼ仕上げてるので、必要な事務手続を終えたら提訴予定。9月中には必ず第一段。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:53／2018/11/10 11:16 URL： https://twitter.com/kk_hirono/status/1289227817092227073 https://twitter.com/shima_chikara/status/1061080025795948545  

> 私への訴訟費用実費カンパは、現状で約300万円集まっております。提訴後、一旦報告させていただきます。 労働弁護団など所属団体で呼び掛けていないこともありますが、全く接点もなかった方含め、多数カンパをいただき、本当に感謝しておりますm(__)m  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:54／2018/11/30 11:31 URL： https://twitter.com/kk_hirono/status/1289227925896572929 https://twitter.com/shima_chikara/status/1068331701993037826  

> 本日、私への大量懲戒請求について、横浜地裁に１陣・３訴訟（被告６名✕３訴訟＝１８名）を提訴しました。 事件番号平成３０年（ワ）第４７４９号（５民）、同第４７８０号（８民）、同第４７８１号（９民） カンパいただいた皆さま、大変お待たせしましたm(__)m ＃大量懲戒請求  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:54／2019/02/15 16:42 URL： https://twitter.com/kk_hirono/status/1289228064279289857 https://twitter.com/shima_chikara/status/1096313751899320320  

> 被害回復のカンパもらった弁護士って、いないはずですよ。 カンパは懲戒請求者への訴訟費用目的です、私がいただいたのは。管理口座も個人名義でなく弁護団名義。 そこは、カンパしてくださった方に誤解与えるので指摘しときますね。 https://t.co/8oz4rZOWeC  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:55／2019/02/16 18:24 URL： https://twitter.com/kk_hirono/status/1289228304348672000 https://twitter.com/shima_chikara/status/1096701871480160256  

> 大量懲戒請求で「損害が無い」「訴訟で儲けている」とか言われると、日頃温厚で知られる私でも、少々ムッとしますね。 ちなみに、同業者から訴訟費用で多くのカンパをいただいた（感謝）。 同業者がカンパしてくれたのは、弁護士だからこそ、被害も訴訟実負担もよく理解しているから。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:56／2019/03/15 10:17 URL： https://twitter.com/kk_hirono/status/1289228428231598081 https://twitter.com/shima_chikara/status/1106363667040239616  

> 【訴訟費用カンパに関するご報告】 皆さまから、現在まで332万6310円のカンパをいただきました。 これまで、郵券・印紙代、提訴予告通知発送作業、被告住所調査費用、代理人弁護士（私、佐々木・北弁護士以外の弁護士）への弁護士費用として、165万6115円を支出させていただきました。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:56／2019/03/17 23:53 URL： https://twitter.com/kk_hirono/status/1289228494711296007 https://twitter.com/shima_chikara/status/1107294009314074625  

> 【訴訟費用カンパに関するご報告】 皆さまから、2019年3月15日時点で332万6310円のカンパをいただきました。ありがとうございます。これまで郵券印紙代、提訴予告通知発送作業、被告住所調査費、代理人弁護士（私、佐々木・北以外の… https://t.co/0C1xrC6zdp  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:57／2019/04/11 13:36 URL： https://twitter.com/kk_hirono/status/1289228588609224705 https://twitter.com/shima_chikara/status/1116198434820644864  

> 原告私の不当懲戒請求事件、横浜地裁で全額認容(33万)判決です。被告6名。欠席判決は2人で、残りは反論した上での判決。 人生初の(自分の)勝訴判決です。嬉しい！ カンパいただいた皆様、代理人の皆様に感謝。 #不当懲戒請求 #勝訴  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:57／2019/06/26 10:39 URL： https://twitter.com/kk_hirono/status/1289228690887282691 https://twitter.com/shima_chikara/status/1143695298390188035  

> @PxRAu990oSW6sIl カンパのお金で印鑑は作っておりません。所員弁護士の押印＆代印で処理しています。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:58／2019/06/30 20:41 URL： https://twitter.com/kk_hirono/status/1289228842259763200 https://twitter.com/shima_chikara/status/1145296410754949120  

> @PxRAu990oSW6sIl @LQ76130865 @sugibow ご心配ありがとうございます！ 神奈川県弁護士会とは、仲良く訴えられているので、協働歩調です（笑） 神奈川県弁護士会の会員からは、多数のカンパもいただいおり、とても感謝しています。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:58／2019/08/23 18:12 URL： https://twitter.com/kk_hirono/status/1289228907279863808 https://twitter.com/shima_chikara/status/1164827824215060483  

> 本日、原告私の訴訟で原告本人尋問の期日。裁判官に私の被害実態を聴いてもらいました。 不当懲戒請求訴訟で、弁護士本人の証人尋問は初（今後も不明）。 尋問されるのは初体験でしたが、代理人のサポートで乗切れました。カンパいただいた皆さま… https://t.co/Nv0jVRFpyB  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:58／2019/09/19 14:17 URL： https://twitter.com/kk_hirono/status/1289229012938584064 https://twitter.com/shima_chikara/status/1174553181184856065  

> 現在、1～18事件を提訴で、被告数合計168名。 なお、カンパ募集開始時以降も懲戒請求がなされ、現在は958件。 これとは別に、損害賠償請求をしたことへの報復的な懲戒請求は別途140件ほど、私や神奈川県弁護士会と日弁連を共同被告と… https://t.co/i6DefRuJN4  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:59／2019/09/20 19:10 URL： https://twitter.com/kk_hirono/status/1289229209299120129 https://twitter.com/shima_chikara/status/1174989323650781184  

> 【カンパの会計報告】 使用内訳は、ある程度全体解決の目途がたった時期にご報告させて下さい。こちらの動きが見えてしまうこともあり、今はこの程度で御容赦を。 なお、カンパの用途に、私の収入補填や出頭時の交通費は含まれておりません（今後もあり得ません）。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 01:00／2019/10/21 09:05 URL： https://twitter.com/kk_hirono/status/1289229340043915265 https://twitter.com/shima_chikara/status/1186070888728297472  

> @hamabou_33 @kumikokatase 現実に、960人を相手に訴訟提起することの負担が重いこと(労力だけでなく実費も)は、訴訟実務を知っていれば簡単に分かることですので、揶揄されても気になりません。 カンパ、弁護団の… https://t.co/0PXMXJeqaN  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 01:00／2019/10/30 17:10 URL： https://twitter.com/kk_hirono/status/1289229385740951552 https://twitter.com/shima_chikara/status/1189454580645416960  

> 本日、原告私の第25次訴訟を横浜地裁に提訴しました（1訴状・被告20名）。 これで提訴済みが合計248件です。 カンパのご支援、どうもありがとうございます。 ＃不当懲戒請訴訟  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 01:00／2020/01/01 12:01 URL： https://twitter.com/kk_hirono/status/1289229445379706881 https://twitter.com/shima_chikara/status/1212207115923677189  

> 明けましておめでとうございます！ 昨年は、多くの皆様にお世話になりました。とくに、大量不当懲戒請求の関係でカンパ含むご支援、ありがとうございました。 今年も、ライフワークの労働問題等を中心に、Twitterで発信していきます。 そ… https://t.co/YcgGWVGsPV  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 01:00／2020/02/21 23:18 URL： https://twitter.com/kk_hirono/status/1289229537927032833 https://twitter.com/shima_chikara/status/1230859281668296705  

> 素晴らしいサイトができました。 報告が途切れがちで恐縮ですが、着々と進展してます。 提訴・勝訴判決が積み重なる一方、私と神奈川県弁護士会を被告とするスラップ訴訟も全国で提訴されてます。 カンパのご支援、宜しくお願いします ⇒不当懲… https://t.co/iI94BpvXKI  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 01:06／2020/03/13 15:17 URL： https://twitter.com/kk_hirono/status/1289231032231669761 https://twitter.com/shima_chikara/status/1238348345778683904  

> 私と神奈川県弁護士会を被告とする損害賠償請求訴訟は、京都・名古屋・奈良（葛城支部）・高松で提起されていて、まだまだ増える様相も。 訴訟対応を依頼する弁護士さんへの費用支払も必要です。 カンパのご支援、継続的に募集中です。宜しくお願… https://t.co/8NjnBVzVBy  

不当懲戒請求問題弁護団 https://t.co/FsJIgdEl7u このページは，弁護士佐々木亮（東京弁護士会所属），弁護士北周士（東京弁護士会所属），弁護士嶋崎量（神奈川県弁護士会所属）に対して 平成29年中に大量に行われた不当な懲戒請求について，

不当懲戒請求問題弁護団 https://t.co/FsJIgdEl7u 和解によるメリット \n 以上の手順で和解がされた場合は，損害賠償請求訴訟を提起せず，刑事上の処罰も求めません。

不当懲戒請求問題弁護団 https://t.co/FsJIgdEl7u 申出方法 \n 和解の申出は，神奈川総合法律事務所の「相談申込みフォーム」（嶋崎弁護士 所属事務所）へお申し込み下さい。

不当懲戒請求問題弁護団 https://t.co/FsJIgdEl7u この申出は，原則として，3名の弁護士に対する和解を希望するご連絡であると判断します。

不当懲戒請求問題弁護団 https://t.co/FsJIgdEl7u 弁護団に対するカンパのお願い \n この弁護団の活動のために，カンパを受け付けております。

不当懲戒請求問題弁護団 https://t.co/FsJIgdEl7u カンパの振込先口座 \n 佐々木弁護士・北弁護士用

不当懲戒請求問題弁護団 https://t.co/FsJIgdEl7u 嶋﨑弁護士用 \n 銀行名：みずほ銀行 \n 支店名：横浜支店（店番357） \n 口座種類：普通 \n 口座番号：4012715 \n 口座名義：不当懲戒請求被害回復カンパ

不当懲戒請求問題弁護団 https://t.co/FsJIgdEl7u 佐々木弁護士・北弁護士用 \n 銀行名：みずほ銀行 \n 支店名：浜松町支店（店番148） \n 口座種類：普通 \n 口座番号：1665961 \n 口座名義：不当懲戒被害回復原告団

不当懲戒請求問題弁護団 https://t.co/FsJIgdEl7u 原告弁護士 \n  佐々木弁護士（@ssk_ryo） \n  \n  嶋﨑弁護士（@shima_chikara） \n  \n  北弁護士（@noooooooorth）

奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中: REGEXP：”カンパ”／嶋﨑量（弁護士）（@shima_chikara）の検索（2018-05-09〜2020-03-13／2020年08月01日00時18分の記録45… https://t.co/EAu9TE6N3S

　なにかの間違いかと思ったのですが，カンパをキーワードに含む嶋﨑量弁護士のツイートの記録は，2020年3月13日のツイートで途切れていました。ちなみに本日は，2020年8月1日になります。

　重要と思える間違いがあっては，北周士弁護士，嶋﨑量弁護士，佐々木亮弁護士にもご迷惑が掛かりかねないというツイートは，スクリーンショットをあわせて記録しました。それを次にリツイートし，佐々木亮弁護士のツイートのまとめ記事に移ります。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-01 01:11／2020/08/01 01:06 URL： https://twitter.com/kk_hirono/status/1289232274047660033 https://twitter.com/s_hirono/status/1289231057577861122  

> 2020-08-01-010540_原告弁護士　佐々木弁護士（@ssk_ryo）　嶋﨑弁護士（@shima_chikara）　北弁護士（@noooooooorth）.jpg https://t.co/GRwTLn0Z5T  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-01 01:11／2020/08/01 01:06 URL： https://twitter.com/kk_hirono/status/1289232292511019008 https://twitter.com/s_hirono/status/1289230984798380032  

> 2020-08-01-010401_カンパの振込先口座佐々木弁護士・北弁護士用.jpg https://t.co/zezW88IOL4  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-01 01:11／2020/08/01 01:06 URL： https://twitter.com/kk_hirono/status/1289232304838029317 https://twitter.com/s_hirono/status/1289230911699968001  

> 2020-08-01-010303_この申出は，原則として，3名の弁護士に対する和解を希望するご連絡であると判断します。.jpg https://t.co/rnlMtYNjdU  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-01 01:11／2020/08/01 01:05 URL： https://twitter.com/kk_hirono/status/1289232320034009088 https://twitter.com/s_hirono/status/1289230838110892033  

> 2020-08-01-005519_嶋﨑量（弁護士）@shima_chikara被害回復のカンパもらった弁護士って、いないはずですよ。カンパは懲戒請求者への訴訟費用目的です、私.jpg https://t.co/INAr69wNWS  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:13／2011/08/06 12:38 URL： https://twitter.com/kk_hirono/status/1289232640923455491 https://twitter.com/ssk_ryo/status/99685703503454208  

> 厳しい状況だとは思うが、たった今、ビギナーズネット（ @beginners_net ）にわずかばかりのカンパをした。本当にわずかだけど（笑）。みなさんもフトコロに余裕があればカンパしてあげましょう（と、菅本先生にツイッターで宣伝してくださいと言われたので実行しました）。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:13／2011/08/06 12:42 URL： https://twitter.com/kk_hirono/status/1289232770128994305 https://twitter.com/ssk_ryo/status/99686688485416961  

> 菅本先生によると「カンパ先： ゆうちょ銀行　０２２１０－７－１１７６８４　口座名義：　ビギナーズネット　★他行からのお振込は、以下の店名・口座番号になります（口座名義は同じです）　店名（店番）：二二九（ニニキュウ）　口座番号：　０１１７６８４」・・・だそうです。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:14／2012/04/22 00:21 URL： https://twitter.com/kk_hirono/status/1289232885220651009 https://twitter.com/ssk_ryo/status/193721222385766403  

> 福島みずほ議員と、けっこう昔に、名刺交換したことがあるからか、国政報告とカンパのお願いが何回か届いたことがある。で、カンパの振込銀行はどこかな、と思ってみたら、みずほ銀行だったんだ。本当だよ。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:14／2018/04/27 18:36 URL： https://twitter.com/kk_hirono/status/1289232990598344706 https://twitter.com/ssk_ryo/status/989800473874972673  

> 不当な懲戒請求に対する費用のカンパを募ります。口座は写真のやつです。印紙や郵券、副本の作成費用（紙代、コピー代）に使用します。ぜひ、ご協力をお願いします。 #不当懲戒   https://t.co/2lzB1n8v9G  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:14／2018/04/28 11:21 URL： https://twitter.com/kk_hirono/status/1289233065978425347 https://twitter.com/ssk_ryo/status/990053368402927616  

> #不当懲戒　のカンパは下記口座へ。お力添えいただければ幸甚です。  みずほ銀行　浜松町支店　普通　１６６５９６１　不当懲戒被害回復原告団  ・印紙代、郵券代、副本作成費（紙代・コピー代）に使います ・懲戒請求者に対する通知や発信者… https://t.co/5gxeKj3c2x  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:16／2018/04/28 11:22 URL： https://twitter.com/kk_hirono/status/1289233429230362624 https://twitter.com/ssk_ryo/status/990053589660778496  

> いただいた金額の合計および使用内容につきましては適宜TwitterやFB等で報告させていただきます。 もし、非常に多くのカンパを頂戴した場合には、今後同様の被害にあった人のためのプール金とさせていただく予定です。引き継ぎ先等につきましても適宜ご報告致します。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:17／2018/05/07 10:26 URL： https://twitter.com/kk_hirono/status/1289233745992511491 https://twitter.com/ssk_ryo/status/993300891531792384  

> カンパ、本当にありがとうございます。ツイッターの通知が非常に多く、お礼が漏れている方もいると思われます。大変失礼しておりますが、ご容赦ください。引き続きよろしくお願いいたします。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:17／2018/05/23 19:40 URL： https://twitter.com/kk_hirono/status/1289233834672713729 https://twitter.com/ssk_ryo/status/999238687073288192  

> 今日は普段は相手方になるだろう先生からもカンパをいただいた。また、先日は、期日の後に、相手方の先生から心配いただいた。ありがたいことだ。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:18／2018/06/06 20:53 URL： https://twitter.com/kk_hirono/status/1289233965413363713 https://twitter.com/ssk_ryo/status/1004330447289978880  

> よくわかんないんだけど、弁護士がカンパを募ると品位を欠くとかって、どういう理屈なの？意味が分からん。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:18／2019/03/11 09:39 URL： https://twitter.com/kk_hirono/status/1289234027325448192 https://twitter.com/ssk_ryo/status/1104904721368641536  

> 余命なんとかが、私や北さんを何億円もの訴額で訴えると息巻いていた件、事件番号と係属部をあるスジから入手したので問い合わせたら、２月に取り下げで終了しておりました。訴訟を謄写したら、改めてお知らせします。しかし、大々的にカンパ集めてやった訴訟を期日指定前に取り下げるって。。。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:19／2019/03/11 11:00 URL： https://twitter.com/kk_hirono/status/1289234151414013953 https://twitter.com/ssk_ryo/status/1104925056562425856  

> 訴訟記録一式を謄写して、このあたりも確認したいところ。読者から多額のカンパを集めて、訴えるまでやったのに、そのあと、なぜか取下げという行動をとっている。極めて不可解である。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:19／2019/03/11 11:02 URL： https://twitter.com/kk_hirono/status/1289234271220056065 https://twitter.com/ssk_ryo/status/1104925653130854400  

> 訴えるので読者からカンパを集める（５万円×〇〇〇名？） ↓ 訴えて印紙を何百万円も納める ↓ 期日前に取り下げる ↓ 印紙代半額返る  なんなのだろう、これ・・。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:20／2019/04/12 18:33 URL： https://twitter.com/kk_hirono/status/1289234380045475840 https://twitter.com/ssk_ryo/status/1116635443913576450  

> 弁護士費用は認められませんでしたが、カンパくださった皆さま、応援してくださった皆さま、強力な呉越同舟弁護団の先生方、ありがとうございました。第一弾は完勝です。あと私の巻き添えになって申し訳ない北さん、嶋崎さん、ホントにごめんなさい。今日の結論でとりあえずホッとしました・・。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:20／2019/11/23 11:10 URL： https://twitter.com/kk_hirono/status/1289234459724673024 https://twitter.com/ssk_ryo/status/1198061148458717185  

> 大体、６０名の提訴で５０万円くらい経費がかかります。もし、まだお力添えいただけるのであれば、引き続きカンパを募集しておりますので、よろしくお願いいたします。 #不当懲戒請求 #大量懲戒請求  https://t.co/PnbxmiaOH2  

　佐々木亮弁護士のカンパをキーワードにしたツイートは5月23日を最後にしているのですが，次の北周士弁護士のツイートを引用リツイートしたものになります。「カンパの総額は920万円になりました。」とあります。

- TW noooooooorth（ノ ー ス ラ イ ム） 日時： 2020/05/23 09:33 URL： https://twitter.com/noooooooorth/status/1263991501404528640  

> カンパの総額は920万円になりました。本当にありがとうございました！なお既に使い切っており現在は手出しで戦っております。カンパがなければ戦い切ることは到底できませんでしたね…。 https://t.co/EODipRdbuC  

　すでにリツイート済みのツイートになります。佐々木弁護士・北弁護士用が口座名義：不当懲戒被害回復原告団，嶋﨑弁護士用が口座名義：不当懲戒請求被害回復カンパとなっているのですが，これも不可解で，総額が増えそうではありますが，いろいろと誤解も与えそうです。

```
弁護団に対するカンパのお願い
この弁護団の活動のために，カンパを受け付けております。
カンパの利用用途
いただいたカンパは，訴訟提起の際の印紙代，郵便費用，副本等の作成費用（印刷費等），代理人の出廷費用，意見書依頼費用，発端となったブログの開設者に関する発信者情報開示請求の弁護士費用など，弁護団が活動していくための費用に使用させていただきます。

被害の回復のためにカンパをお願いするものではありません。事件が完全に終了した際に余剰を生じたときは，同種の被害を受けた弁護士に対する支援のため，あるいは，不当な懲戒請求の手続による負担を受けた弁護士会等への寄付をするなど，弁護団において協議のうえ使用させていただくことをご了解ください。

カンパの必要性
多数の懲戒請求者に対する提訴には多額の印紙代・郵便費用の予納が必要となります。また，主要な争点について研究者による意見書を依頼しました。そのため，2019年11月末時点で，いずれのカンパ口座も残金が少なくなりつつあります。これまでのご支援に感謝を申しあげるとともに，さらなるご支援を，可能な範囲でお願いいたします。

カンパの振込先口座
佐々木弁護士・北弁護士用
銀行名：みずほ銀行
支店名：浜松町支店（店番148）
口座種類：普通
口座番号：1665961
口座名義：不当懲戒被害回復原告団
嶋﨑弁護士用
銀行名：みずほ銀行
支店名：横浜支店（店番357）
口座種類：普通
口座番号：4012715
口座名義：不当懲戒請求被害回復カンパ
原告弁護士
 佐々木弁護士（@ssk_ryo）

 嶋﨑弁護士（@shima_chikara）

 北弁護士（@noooooooorth）

［source：］不当懲戒請求問題弁護団 https://futo-choukai-seikyu.net/
```

　上記にまとめて引用しましたが，「事件が完全に終了した際に余剰を生じたときは，同種の被害を受けた弁護士に対する支援のため，あるいは，不当な懲戒請求の手続による負担を受けた弁護士会等への寄付をするなど，弁護団において協議のうえ使用」とあります。

　弁護士会への寄付というのはまったく初めて目にしたのですが，寄付をした人への見返りが全く感じられないのもこのカンパ募集の特徴です。大崎事件のクラウドファンディングでは，心からの感謝のメッセージなどというものがありました。

　「被害の回復のためにカンパをお願いするものではありません。」ともこのホームページにはあるのですが，すでに数々の勝訴判決を受けているとツイートとしながら，賠償金を得たという報告は，3人の弁護士のツイートにも全く見当たらないものとなっています。

　つい最近は，最高裁での勝訴判決が続出しているというようなツイートを見ているのですが，民事裁判が確定すれば債務名義として強制執行も可能，任意に支払いがなければ画餅に帰すともいわれるところですが，回収の見込みを含めたそのあたりの説明も全く見られないところです。

　最高裁が勝訴判決と書いてしまいましたが，刑事事件の場合は書面審理のみが原則で，口頭弁論がなければ決定となり，口頭弁論が開かれた場合が判決となります。民事裁判の場合は情報も少なくわかりづらいのですが，上訴にお金の負担がかかるとも過去に勉強をしています。

　いずれにせよ，最高裁で勝訴が続いているとのことなので，お墨付きをもらったかたちにもなりそうですが，一つ間違うと出資法などの刑事事件として，警察や検察が捜査をする可能性もあるように思えてきました。

　ツイートで写真が公開されているのも銀行口座の表だけです。他の部分はモザイク処理をするにしても，振込の日付と金額は公開して不思議はないように思います。私も祭礼委員会の会計として決算報告書を作成し町内会長，氏子総代の監査を受け，宇出津の各町内各戸の回覧にすることをやってきました。

〈〈〈：Linux Emacs： 2020-08-01（土曜日）01：48 　〈〈〈

