* 「「ドクター・キリコになりたい」　京都ＡＬＳ女性嘱託殺人　逮捕の医師、ツイッターに繰り返し投稿か　 | 京都新聞 」という市川寛弁護士のツイート
  :LOGBOOK:
  CLOCK: [2020-07-28 火 11:34]--[2020-07-28 火 15:11] =>  3:37
  :END:

:CATEGORIES: 市川寛弁護士

〉〉〉：Emacs： 2020-07-28（火曜日）11：34　 〉〉〉

 - 2020年07月28日09時58分の登録： ＼弁護士 市川 寛　@imarockcaster42＼「ドクター・キリコになりたい」　京都ＡＬＳ女性嘱託殺人　逮捕の医師、ツイッターに繰り返し投稿か　 | 京都新聞 http://hirono2014sk.blogspot.com/2020/07/imarockcaster42_28.html

　週刊少年チャンピオンの連載と記憶しているブラックジャックですが，これも昭和40年代の終わりから連載が始まったように記憶にあります。連載は長く続いていたように思うのですが，週刊少年チャンピオンをほとんど読まなくなったとも記憶にあるので，いつまで続いたのはわかりません。

　週刊少年チャンピオンを読まなくなった頃，宇出津の千間書店の漫画の単行本の棚に，同じ手塚治虫の漫画で「火の鳥」を見かけるようになったと記憶にあるのですが，手にして開くか，手にすることもなかったのかという記憶しかないものの，割と強く印象に残っていました。

火の鳥 (漫画) - Wikipedia https://t.co/4iTVdmpXCn

　比較的最近になって情報を見かけるようになった手塚治虫の火の鳥ですが，きっかけは深澤諭史弁護士のリツイートにもなっていたと思うアッサジであったように思います。

　市川寛弁護士のツイートにある記事を読むと，ドクター・キリコがブラックジャックの登場人物のように書かれていました。キリコというのは，子供のような大人のような女の子で，ブラックジャックの手術の助手をしていた登場人物のことかと思っていました。

　調べたところ，その女の子はキリコではなくピノコだったのですが，双子の姉の腫瘍から生まれた話など，これまで全く知らなかったことがわかりやすい情報としてまとめられていました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-28 11:56／2020/07/28 10:04 URL： https://twitter.com/kk_hirono/status/1287945091403755520 https://twitter.com/hirono_hideki/status/1287916730778415104  

> ブラックジャックピノコにモデル!誕生秘話･正体は双子姉の病気腫瘍 https://t.co/egw9J27PMU  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜asahi_nagoya（朝日新聞名古屋編集局） 日時：2020-07-28 11:57／2020/07/27 19:08 URL： https://twitter.com/kk_hirono/status/1287945279245754369 https://twitter.com/asahi_nagoya/status/1287691231879819264  

> 男性3人に車突っ込み1人死亡、無差別殺害図る？　豊橋 https://t.co/pQloB1Fm7O  27日午後2時半ごろ、愛知県豊橋市の路上で、除草作業中の男性3人に、男が運転する車が突っ込んだ。3人は病院に搬送されたが、1人が死亡した。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜tv_asahi_news（テレ朝news） 日時：2020-07-28 11:58／2020/07/27 18:19 URL： https://twitter.com/kk_hirono/status/1287945409915101184 https://twitter.com/tv_asahi_news/status/1287678885153234982  

> 【速報】路上の男性3人に殺意を持って車で突っ込み男性1人死亡、2人搬送　愛知・豊橋市 https://t.co/thR32iDcU8  

「神になりたかった」路上の男性3人に車で突っ込んだ男が逮捕 愛知県豊橋市 / Twitter https://t.co/4FOLN9D2rM

　Twitterのトレンドに「「神になりたかった」路上の男性3人に車で突っ込んだ男が逮捕 愛知県豊橋市」とあり，昨夜も見ていたニュースでしたが，愛知県とは記憶にあったものの，豊橋市というのは，このトレンドで初めて知ったように思いました。被告発人安田敏の白菜散乱も思い出します。

　豊橋市といえば，以前は，豊橋刑務所が交通刑務所という話を聞くことがあったのですが，他にもっと有名だった市原刑務所を含め，近年，交通刑務所という話をまったく見かけていないように思いました。

　キリコは，ガラス細工の工芸品としてテレビで見かけることもありますが，私の生まれ育った能登では，神様を先導する灯籠が巨大化したものとして，とても身近な言葉になります。ドクター・キリコの記憶がなかったのは不思議にも感じるのですが，見たことがなかったのか確信は持てません。

```
「切籠（キリコ）」または「奉燈（ほうとう）」と呼ばれる高さ数メートル〜十数メートルの巨大な切子灯籠を使うことを特徴とするものである。地域によって御明かし（おあかし）とも呼ばれる。主として7月から10月に掛けて夏祭り・秋祭りとして、現在も能登の約137の地区（不定期を含む）で行われており、疫病退散を願って始まったとされるものが多い。

1997年（平成9年）12月4日に「能登のキリコ祭り」として、国の「記録作成等の措置を講ずべき無形の民俗文化財」に選択され［1］、2015年（平成27年）4月24日に文化庁が【日本遺産】最初の18件の一つとして「灯り舞う半島 能登 ～熱狂のキリコ祭り～」の名称で認定した［2］。

［source：］能登キリコ祭り - Wikipedia https://ja.wikipedia.org/wiki/%E8%83%BD%E7%99%BB%E3%82%AD%E3%83%AA%E3%82%B3%E7%A5%AD%E3%82%8A
```

　ちょっと忘れていたような気もするのですが，「国の「記録作成等の措置を講ずべき無形の民俗文化財」に選択」というのが，弁護士ツイートの記録作成に大きな影響を与えたと思います。弁護士鉄道の記録です。

　前にも調べたことがあるように思うのですが，ブラックジャックの連載の時期を調べておきたいと思います。調べたようには思うのですが，内容が記憶に残っていない感覚です。

```
『ブラック・ジャック』（BLACK JACK）は、手塚治虫による日本の漫画作品。『週刊少年チャンピオン』（秋田書店）にて1973年11月19日号から1978年9月18日号にかけて連載したのち、1979年1月15日号から1983年10月14日号にかけて不定期連載された。全242話。略称はB・J。

［source：］ブラック・ジャック - Wikipedia https://ja.wikipedia.org/wiki/%E3%83%96%E3%83%A9%E3%83%83%E3%82%AF%E3%83%BB%E3%82%B8%E3%83%A3%E3%83%83%E3%82%AF
```

　昭和48年から連載が始まったとあります。昭和53年まで5年ほどの連載だったらしく，これは意外に早く終わっていたように感じました。「1979年1月15日号から1983年10月14日号にかけて不定期連載」というのは知らなかったと思いますし，不定期連載とは初めて見た気がします。

　ブラック・ジャックが正しいようですが，ブラックジャックというトランプのゲームがあったことを思い出しました。ゲームの内容が思い出せないですが，そもそもジャックの意味をしらないことに気が付きました。電波ジャックというのは昔，テレビで見かけたような気はします。

```
電波ジャック（でんぱジャック）とは、電気通信における正規の伝送路を乗っ取り、正規の受信者に向けて独自の内容を送信することをいう。

なお、「電波ジャック」はハイジャックに由来する日本独自の表現であり、英語では「Broadcast signal intrusion（放送信号割り込み）」又は、「Broadcast pirating」と呼ぶ。

［source：］電波ジャック - Wikipedia https://ja.wikipedia.org/wiki/%E9%9B%BB%E6%B3%A2%E3%82%B8%E3%83%A3%E3%83%83%E3%82%AF
```

　昭和の時代は身近でもあったハイジャックという言葉をいつのまにかすっかり忘れていたことに気が付きました。ジャックというのは乗っ取るという意味があるようです。他にも意味はあるのかもしれないので調べて確認しておきます。

ジャック(じゃっく)とは - コトバンク https://t.co/ZPUYdDEE2P

　乗っ取るという意味は書かれていなかったのですが，トランプの絵札とあるので10の次のJのことのようです。ジャックと呼んでいた記憶はあまりないのですが，トランプは平成以降，ほとんど見たこともないように思います。これも昭和の時代は身近なものでした。

　もう4週間ほど前になりますか，数年前から何度か時間を掛けて探していた，手塚治虫の短編漫画をようやく見つけ出すことが出来ました。漢字2文字だったとも思うのですが，不思議と記憶に薄かったタイトルで，実は今も思い出すことが出来ず，不思議に思っています。

〈〈〈：Linux Emacs： 2020-07-28（火曜日）12：44 　〈〈〈

* 宮城県名取市から思い出した，平成3年4月頃，被告発人安田敏が輪島屋鮮冷の運転手として金沢市場輸送に来た頃の状況
  :LOGBOOK:
  CLOCK: [2020-07-28 火 15:11]
  :END:

:CATEGORIES: 被告発人安田敏,金沢市場輸送

〉〉〉：Emacs： 2020-07-28（火曜日）15：11　 〉〉〉

　福島県と宮城県の県境は，宮城県が岩沼市で，国道4号線と国道6号線が交わった辺りが宮城県と記憶にあるのですが，その付近に自衛隊の駐屯地があって，岩沼市ではなかったような記憶があります。ちょうど平成3年の4月頃に爆弾の荷物を運びました。

石川製作所　爆弾 - Google 検索 https://t.co/k86px1AbRF

防衛関連株は大波乱、代表格の石川製作所に信用規制が発動され週末要因も影響 | 株式投資情報　総合　日本インタビュ新聞 https://t.co/dGCyO0aRu4 2017/4/14 11:48:18株式投資ニュース

　石川製作所の場所が思い出せないのですが，金沢市場輸送にいた頃から爆弾や魚雷をちょくちょく積みに行き，福島県と群馬県の大きな火薬工場，自衛隊の基地や駐屯地に運ぶようになりました。自衛隊は少なかったかもしれません。

　他にもあったように思うのですが，今思い出せるのは青森県八戸市の航空自衛隊の基地，そして福島県との県境に近い自衛隊で基地ではなく駐屯地となっていたように思います。宮城県の自衛隊ということで検索すれば情報がすぐに見つかりそうです。

自衛隊 岩沼市 - Google 検索 https://t.co/EMSK0rKSN4 宮城県柴田郡柴田町大字船岡 字, 大沼端１−１

自衛隊 岩沼市 - Google 検索 https://t.co/gSSFZZh2g8]] 宮城県岩沼市下野郷北長沼

　ページタイトルがGoogleの検索ワードになっていました。岩沼市とあるのが陸上自衛隊岩沼訓練場，柴田郡柴田町と住所があるのが，陸上自衛隊船岡駐屯地となっています。

　国道4号線より山の方に入ったという記憶があるので，この船岡駐屯地に間違いはなさそうですが，平成3年当時は違った名称になっていたような気もします。

　船岡駐屯地というのは聞き覚えがないのですが，さきほど漢字2文字のように思い出しかけていた手塚治虫の短編漫画ですが，さきほど思い出したのは「ガラスの脳」になります。これも似たような感覚で，以前に見聞きをしたような感覚が乏しかったのです。

石川製作所 - Google 検索 https://t.co/EEzwKibXak]] 石川県白山市福留町２００

　石川製作所を調べると，白山市福留町とありました。この福留町というのは，逆に記憶というか脳にこびりついたような感覚の地名になります。この検索をする前，石川製作所は当時の石川郡野々市町，現在の野々市市の可能性が高いように考えていました。白山市は当時の松任市になります。

　福留町は，トラックで走行中，たびたび標識を見かけていたように思うのですが，埼玉県の辺りにも似たような地名があったり，似たような福増町という地名も見ていたような記憶があって，今の記憶のままだと白山市のどのあたりになるのか正直わかりません。

　長距離以外の市内配達などの仕事では，地図を所持することも地図をみることもほとんどなかったと思うのですが，国道8号線で手取川を渡る付近というのは，思いの外，海に近いのだと思いました。国道8号線は陸橋になるのか，手取川の橋や川を見たという記憶はない気がします。

　手前に斜めに入る旧道のような道路があって，そこでは手取川の大きな橋を渡り，橋を渡ってすぐ左手にあるのが手取フィッシュランドでした。2年ほど前にはテレビで中継を見たことがありました。最近はテレビCMも見かけなくなっていますが，そのままあると思います。

　自衛隊や爆弾というのは国防に関わる問題でもあり，あまり具体的にするのを避けていたのですが，福島県の火薬工場は日本工機，群馬県にあるのは中国化薬でした。前に調べたとき，中国化薬の本社は広島県とかの中国地方にあるらしく，それで中国化薬という名前になっているようです。

日本工機 - Google 検索 https://t.co/zBFASCQDWI]] 日本工機（株） 白河製造所

　白河製造所というのは初めてみたように思います。住所が福島県西白河郡西郷村となっています。白河市なのかと思っていました。栃木県との県境に近いと確認しました。国道4号線から少し日本海の方向に入ったというのは記憶どおりのようです。

　同じ頃に初めて山形市の市場に筍を運んだという記憶があるのですが，照明の暗い感じが印象に残る市場で，それとよく似た印象を受けたのが，平成4年3月30日の深夜から翌31日の未明の時間に，これも初めて行った静岡県浜松市の市場になります。

　他に，横浜の市場と徳島市の市場も照明が暗さが気になったことで印象に残っています。

　宮城県の自衛隊の駐屯地では，同じ荷物を積んできた輪島屋鮮冷の大型車と一緒になりました。運転手のこともいくらか記憶に残っているのですが，荷物を積み込んだ前日にも会っているという記憶があって，金沢市場輸送の会社前であったように思います。

　金沢市場輸送の軽油の給油機は，たしか後ろがブロック塀になっていて，ブロック塀の先はパチンコオークラの駐車場の一部になっていました。その辺りで会ったという気がするのですが，同じ頃に，輪島屋鮮冷の4トン保冷車に乗ってきた被告発人安田敏とも会っています。

　被告発人安田敏のときは，荷物の積み替えだったと思います。船凍イカとも思うのですが記憶がぼやけています。被告発人安田敏からはいきなり自宅アパートに電話があって，そのときに金沢市場輸送に入社するような話となっていました。

　輪島屋鮮冷が金沢市場輸送の仕事をするようになったのは，その平成3年の春頃と思うのですが，１つ別の記憶があって，当時の松任市の海の方の出荷場で，輪島屋鮮冷の大型車の運転手と一緒になったことがありました。年は若かったと思います。

　スイカなのか大根なのか記憶がはっきりしないのですが，ちょうどそのあたりの出荷場で，一度大根を積み込んだ仕事の記憶ははっきりしています。それが京都市の市場行きの運行だったとも思うのですが，異例の珍しい仕事でした。

〈〈〈：Linux Emacs： 2020-07-28（火曜日）16：43 　〈〈〈


* 深澤諭史弁護士のリツイートで見た「アッサジ」，
