#+TITLE: "告発状・参考資料"
#+AUTHOR: 廣野秀樹
#+EMAIL:  hirono2013k@gmail.com
#+DATE: 2020-06-25 20:19:37 +0900
FILE_NAME: 2020-06-25-201937_告発状・参考資料.org
CATEGORY: 金沢地方検察庁御中
tags:  金沢地方検察庁
記事タイトル名の文字数：8　保存ファイル名の文字数：30

#contents

* 弁護士

** 野田隼人弁護士（滋賀弁護士会）

*** 秋重実弁護士（京都弁護士会）のTwitterタイムラインで見かけた「鳥獣人物戯画」の問題

**** 「『鳥獣人物戯画』の写真の利用とを区別していないと読み取られたことにびっくりしていますよ。」という野田隼人弁護士（滋賀弁護士会）のツイート

:CATEGORIES: 野田隼人弁護士

- RT akishigemakoto（MakotoAkishige（civilista））｜nodahayato（野田隼人） 日時：2020/06/21 18:48／2020/06/21 18:45 URL： https://twitter.com/akishigemakoto/status/1274640429527429120 https://twitter.com/nodahayato/status/1274639569032327170

> RT @nodahayato: 二次媒体の話なんて全く書いてないのに『鳥獣人物戯画』の利用と『鳥獣人物戯画』の写真の利用とを区別していないと読み取られたことにびっくりしていますよ。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-06-25 20:38／2020/06/25 20:22 URL： https://twitter.com/kk_hirono/status/1276117657574498304 https://twitter.com/s_hirono/status/1276113431033073664  

> 2020-06-25-172657_MakotoAkishige（civilista）さんがリツイート野田隼人@nodahayato·6月21日二次媒体の話なんて全く書いてないのに『鳥獣人物.jpg https://t.co/n6AwdbNHCH  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-06-25 20:39／2020/06/25 20:22 URL： https://twitter.com/kk_hirono/status/1276117763652587520 https://twitter.com/s_hirono/status/1276113504471150594  

> 2020-06-25-172812_野田隼人さんはTwitterを使っています　「著作権は切れていて、関連する意匠も商標も登録されていなさそうなので、何を言っているのかよく分からない。　『鳥.jpg https://t.co/B82xm6JZhw  

　スクリーンショットの記録は本日6月25日17時26分頃となっています。ちょうど新しいことを始めようとするタイミングだったのですが，「鳥獣人物戯画」というのは能都中学校で歴史の授業が始まった早い段階で，教科書で見たという記憶があります。

　「鳥獣人物戯画」が正式名称らしいというのも，この秋重実弁護士による野田隼人弁護士のツイートのリツイートで初めて知ったと思うのですが，「人物」が入っていることに新しい発見を感じました。もともと妖怪に近いイメージがあり，それが弁護士のイメージとも重なっていたのです。

 - 2020年06月25日20時52分の登録： ＼野田隼人　@nodahayato＼二次媒体の話なんて全く書いてないのに『鳥獣人物戯画』の利用と『鳥獣人物戯画』の写真の利用とを区別していないと読み取られたことにびっくり http://hirono2014sk.blogspot.com/2020/06/nodahayato_25.html

 - 2020年06月25日20時53分の登録： ＼MakotoAkishige（civilista）　@akishigemakoto　RT：　@nodahayato＼二次媒体の話なんて全く書いてないのに『鳥獣人物戯画』 http://hirono2014sk.blogspot.com/2020/06/makotoakishigecivilistaakishigemakotort.html

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜usijoe（Mikami Joe） 日時：2020-06-25 20:58／2020/06/21 18:38 URL： https://twitter.com/kk_hirono/status/1276122530621714432 https://twitter.com/usijoe/status/1274637893412110336  

> この人は本当に弁護士何でしょうか？自由に使いたければ、人様が撮影した媒体ではなく、自ら許可を取って撮影した二次媒体が必要なことを知らないのか？びっくりだよ。 https://t.co/tyniSqBXH8  

　本日2020年6月25日に，初めて知ったというか理解したと思ったのは，上記のようなツイートのURLを引用したツイートのことを「返信つきリツイート」とするようです。リツイートのリンク部分を開くと２つに分かれていることは分かっていました。

　ちょっと勘違いしていました。実際にリンクを開いてみるとリツイートに「コメントあり」とありました。今後は「コメントありリツイート」と表記したいと思います。これまで「ツイートのURLの公式引用」などとしていたスタイルのツイートになります。

@nodahayato ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@nodahayato）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW nodahayato（野田隼人） 日時：2020/06/21 12:20 URL： https://twitter.com/nodahayato/status/1274542648863232005  

> 著作権は切れていて、関連する意匠も商標も登録されていなさそうなので、何を言っているのかよく分からない。  
>   
> 『鳥獣人物戯画』を無断で商用利用はできません。 | 和柄・和風デザイン・伝統文様 https://t.co/M98k0FY2sO  

```
高山寺の関係者にお尋ねしたところ、無知か確信犯かは判りませんが無断で不正使用する業者は後を絶たないそうです。時々目に余る無断使用者に対しては法的措置を取られているそうです。

［source：］『鳥獣人物戯画』を無断で商用利用はできません。 | 和柄・和風デザイン・伝統文様 https://ameblo.jp/jj9999/entry-12336956851.html
```

　少し引用をしましたが，野田隼人弁護士のツイートに紹介があったブログ記事になります。ページタイトルには見当たらないですが，初めに開いたとき，少ししてからアメブロの記事だとわかりました。初めはお寺のホームページなのかと思ったからです。

　「『鳥獣人物戯画』を所有している高山寺」と記事にありますが，これはテレビのバラエティ番組で見たお寺だと思うと同時に，滋賀県のお寺に間違いないと思ったのですが，調べるとすぐに間違いで，京都のお寺だということがわかりました。

　京都のお寺でも滋賀県に近いことをイメージしていたのですが，それも外れていました。国道162号線沿いに近いようですが，この国道のことも初めて知りました。

**** 「著作権法の大家である小倉先生のnote（Tweetの４０分後）」という野田隼人弁護士のツイート，「鳥獣人物戯画」と小倉秀夫弁護士

@nodahayato ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@nodahayato）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW nodahayato（野田隼人） 日時：2020/06/21 22:36 URL： https://twitter.com/nodahayato/status/1274697602794000384  

> 著作権法の大家である小倉先生のnote（Tweetの４０分後）  
>   
> https://t.co/zMafEjqo2j  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-06-26 10:01／2020/06/25 20:22 URL： https://twitter.com/kk_hirono/status/1276319532198453253 https://twitter.com/s_hirono/status/1276113577846255617  

> 2020-06-25-172845_野田隼人さんはTwitterを使っています　「著作権法の大家である小倉先生のnote（Tweetの４０分後）　　Twitter.jpg https://t.co/moVMIXsjyq  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-06-26 10:01／2020/06/25 20:22 URL： https://twitter.com/kk_hirono/status/1276319553698492416 https://twitter.com/s_hirono/status/1276113651175317505  

> 2020-06-25-172918_鳥獣人物戯画の商用利用｜小倉秀夫｜note.jpg https://t.co/p6rZrL2uwN  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-06-26 10:01／2020/06/25 20:23 URL： https://twitter.com/kk_hirono/status/1276319575106174976 https://twitter.com/s_hirono/status/1276113724391059457  

> 2020-06-25-173214_鳥獣人物戯画の商用利用｜小倉秀夫｜note.jpg https://t.co/HmlU24akbF  

　時刻は6月26日10時01分です。スクリーンショットの記録は昨日の夕方の17時半頃のものとなっていました。滅多に名前を見かけなくなった小倉秀夫弁護士ですが，野田隼人弁護士が著作権法の大家と評価しているのも意外でした。

```
このようにみると、『鳥獣人物戯画』を所有している高山寺が著作権以外の新たな権利登録を行なっている可能性は乏しいように思います。
　こういう発言を、部外者である成願氏が勝手に吹聴している分には法的な問題は起きないのかもしれませんが、高山寺が積極的にそういうことをWebサイトなどで表示場合には、「鳥獣人物戯画」の商用利用について独占権がないにもかかわらず、そのような権限があるかのように誤認させるような表示をしたことになりますから、２条１項２０号の不正競争行為となる危険があります。なので、高山寺におかれましては、慎重な行動が求められるところです。

［source：］鳥獣人物戯画の商用利用｜小倉秀夫｜note https://note.com/benli/n/nfa2c926ac1ad?fbclid=IwAR2XgxED0mkImcLNnpri71GxngISRo44joQFRq1TIyUnwVSZ2zWgaDF7pnM
```

　小倉秀夫弁護士は，上記に引用をした通り，高山寺が「鳥獣人物戯画」の商用利用について独占権がないにもかかわらず、そのような権限があるかのように誤認させるような表示をしたことになり，不正競争行為となる危険があります，と指摘をしています。

　最近はほとんどみかけない不正競争防止法という法律ですが，小倉秀夫弁護士はその専門書を出していたように思います。小倉秀夫弁護士が専門とする著作権と不正競争防止法の関係が前から疑問には思っていました。ちょっと確認をしておきます。

 - » 小倉秀夫弁護士 不正競争防止法 - Google 検索 https://t.co/jPvQwR475a

 - » 不正競争防止法 平成27年改正の全容 Guideline of Unfair Competition Prevention Law latest revised edition | 小倉 秀夫 |本 | 通販 | Amazon https://t.co/2JpQ2OWJle

 - » 不正競争防止法コンメンタ－ル / 金井 重彦/山口 三恵子/小倉 秀夫【編著】 - 紀伊國屋書店ウェブストア https://t.co/EQsU9bG217 金井 重彦/山口 三恵子/小倉 秀夫【編著】

 - » 不正競争防止法 / 小倉 秀夫【著】 - 紀伊國屋書店ウェブストア https://t.co/BlNvI8CL2x １９６８年生。東京平河法律事務所パートナー弁護士、中央大学法学部兼任講師／明治大学法学部兼任講師。知的所有権研… https://t.co/vH0Qhzb1fo

 - » 量産型懲戒請求を受けた小倉秀夫弁護士が第３者に対して起こした裁判、１人につき１０万円、推定総額９６００万円の請求額は妥当なのか | MEDIA　KOKUSYO https://t.co/2njTDQ3EYE

　ちょっと意外な記事の発見になりました。２０％ぐらいは前に読んでいるような気もするのですが，「鳥獣人物戯画」のような小倉秀夫弁護士という人物の不思議さを感じる記事の内容でした。

**** 「量産型懲戒請求を受けた小倉秀夫弁護士が第３者に対して起こした裁判、１人につき１０万円、推定総額９６００万円の請求額は妥当なのか」という2018年11月の記事

```
Ａさんが小倉弁護士の量産型損害賠償請求を問題としたのは、それにより懲戒請求者が心理的圧迫を受ける点である。また、量産型懲戒請求が違法かどうかの司法判断を待たずに和解に向けた行動を取った事実である。また、和解後の懲戒請求行為に対して、一定の規制を求めてきたことである。さらにこうした事例が「詐欺のモデルケース」を作りかねない状況を生む懸念である。

ここでいう「詐欺のモデルケース」とは、ネットを利用して和解を呼びかけることにより、法的な知識を持たない大半の懲戒請求者の恐怖心を煽って、極めて合理的に金銭を徴収する行為であって、「振り込め詐欺」の類型とは異なる。

この裁判では、法律の専門知識を持たない普通の市民が、弁護士の行動に不信感を感じた場合、懲戒請求を申し立てることの是非が問われそうだ。最高裁の判例に照らし合わせてみると、共謀罪を懲戒事由にすることにはかなり無理があり、懲戒請求の根拠を欠いている可能性が高いが、だからと言って、法曹界に対する一般市民の疑問や不信感を、法解釈だけで切り捨てることができるのか？あるいは訴訟で対抗していいのか？このあたりがジャーナリズムの検証点になりそうだ。

［source：］量産型懲戒請求を受けた小倉秀夫弁護士が第３者に対して起こした裁判、１人につき１０万円、推定総額９６００万円の請求額は妥当なのか | MEDIA　KOKUSYO http://www.kokusyo.jp/justice/13511/
```

　上記の引用部分にあるのは，小倉秀夫弁護士が「繰り返しになるがＡさんは、「余命三年時事日記」の呼びかけに応じて、小倉弁護士に懲戒請求書を送付した一人ではない。」という懲戒請求を受けたことと，それに対して小倉秀夫弁護士が損害賠償裁判を起こした，という経緯です。

　小倉秀夫弁護士が和解の呼びかけをネットの行動として行ったという情報は見かけていましたが，その後，どうなったのか続報を見ることはなかったように思います。小倉秀夫弁護士に対する懲戒請求の結果も同じです。

　この弁護士大量懲戒請求の問題は，佐々木亮弁護士，嶋﨑量弁護士，北周士弁護士がメインの問題でしたが，時間の浪費にもなるので深入りはしないようにしていました。皆無ではないと思いますが，余り取り上げることもしてこなかったと思います。

　この問題は，佐々木亮弁護士，嶋﨑量弁護士，北周士弁護士らが国民の裁判を受ける権利と，裁判所の業務負担の大きさが深刻な社会問題性を孕んでいるとは考えていました。すでに弁護士という職業が末期的な段階なので，ここまでやったのかという見方もありました。

　佐々木亮弁護士，嶋﨑量弁護士は労働問題で大きなアピールをしてきた弁護士で，嶋﨑量弁護士においては労働者の自殺問題でテレビにも出ていました。北周士弁護士も顧問弁護士としての顧問先のことなどをネットで発言し，それだけでもとても忙しそうに見えていました。

　嶋﨑量弁護士は，新型コロナウィルス問題で，いちはやく対応をアピールしていましたが，その頃には大量懲戒請求に関するツイートはほとんど見かけなくなっていました。佐々木亮弁護士のツイートをリツイートしたものは見かけていたかもしれません。

　その嶋﨑量弁護士のTwitterもここしばらくは開いていないのですが，気になる問題を読み始めれば，それも時間を使ってしまうことになるので，それを避ける傾向があったとも言えます。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-06-26 10:55／2020/06/04 13:54 URL： https://twitter.com/kk_hirono/status/1276333283308007425 https://twitter.com/shima_chikara/status/1268405732539371521  

> 少し前の記事ですが、退職強要・解雇・雇い止めのご相談が増えてきたのであげておきます。労働者には、争うみちもあることは、知って欲しい。 ⇒　新型コロナによるリストラは泣き寝入りもやむなし？~労働者が取り得る選択肢とは~(嶋崎量) -… https://t.co/Smu5OlHgIw  

　上記が嶋﨑量弁護士のTwitterアカウントで固定されたツイートとなっているものです。労働法や労働問題は得意分野なのでしょう。プロフィールにも「日本労働弁護団常任幹事、ブラック企業対策弁護団副事務局長、ブラック企業対策プロジェクト事務局長。」とあります。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-06-26 10:59／2020/06/26 08:26 URL： https://twitter.com/kk_hirono/status/1276334238728548352 https://twitter.com/shima_chikara/status/1276295703828918272  

> 正に闇。 https://t.co/7lj5efdfUb  

　上記のツイートにあるのは次の記事です。今朝，Twitterに「過払い金CMの大手弁護士法人」というトレンドがあったので，そこから見つけて読みました。ずっとくすぶり続けてきた問題が，一度に表面化したという感想でした。

　嶋﨑量弁護士は「正に闇。」としていますが，嶋﨑量弁護士や佐々木亮弁護士らの大量懲戒請求への対応の方が，根深い闇を感じてきました。ネットの情報は多く，納得のものが多いのですが，マスコミは最初の頃に弁護士らを有利に取り上げた後は，放置か無視という感じです。

```
〉　小倉弁護士にしても、佐々木亮弁護士にしても、懲戒請求に対するカウンターで莫大な賠償金を手にする可能性がある。筆者には、これが弁護士本来のありかたとは思えない。早急に訴訟を取り下げるべきだろう。

［source：］量産型懲戒請求を受けた小倉秀夫弁護士が第３者に対して起こした裁判、１人につき１０万円、推定総額９６００万円の請求額は妥当なのか | MEDIA　KOKUSYO http://www.kokusyo.jp/justice/13511/
```

　そういえば，長い間，情報を見かけなかった，この弁護士大量懲戒請求問題ですが，2,3日前，「謄写」というまとめ記事を作成し，読み進めていたところ，意外な発見がありました。弁護士会に対する負担です。その前に，Twilogで確認しておきたいことがあります。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-06-26 11:10／2018/12/16 10:18 URL： https://twitter.com/kk_hirono/status/1276337076577767424 https://twitter.com/hirono_hideki/status/1074111591665217536  

> 量産型懲戒請求を受けた小倉秀夫弁護士が第３者に対して起こした裁判、１人につき１０万円、推定総額９６００万円の請求額は妥当なのか | MEDIA　KOKUSYO https://t.co/2MWwXMOCej  

　〉　小倉弁護士にしても、佐々木亮弁護士にしても、懲戒請求に対するカウンターで莫大な賠償金を手にする可能性がある。筆者には、これが弁護士本来のありかたとは思えない。早急に訴訟を取り下げるべきだろう。

　そういえば，長い間，情報を見かけなかった，この弁護士大量懲戒請求問題ですが，2,3日前，「謄写」というまとめ記事を作成し，読み進めていたところ，意外な発見がありました。弁護士会に対する負担です。その前に，Twilogで確認しておきたいことがあります。

 - » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「量産型懲戒請求を受けた小倉秀夫弁護士」の検索結果 - Twilog https://t.co/HIgdnHTyLk

　２０％が既読の可能性という見解を前もってしてしていましたが，既読の記事であったらしいと確認をしました。記事のツイートはメモと同時に，既読の印とすることも意識してやっています。数年経つとわからなくなったり，似たような見出しの別の記事というのもありうるからです。

**** 小倉秀夫弁護士の2018年5月21日のツイートで発見した，「大量「懲戒請求」で弁護士会にジレンマ、数百万円の郵送費と「弁護士自治」の間で」という記事

 - 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中: REGEXP：”謄写”／データベース登録済みツイート：2020年06月24日01時26分の記録：ユーザ・投稿：125／244件 http://hirono2014sk.blogspot.com/2020/06/regexp202006240126125244.html#p100

 - （100／244） TW Hideo_Ogura（小倉秀夫） 日時： 2018-05-21 02:09:00 +0900 URL： https://twitter.com/Hideo_Ogura/status/998249242341785600

> https://t.co/EfI54NgwRT RT @riosis11: @Hideo_Ogura これは？ ＞福岡県弁護士会は対象弁護士の答弁書は綱紀委員会が承諾すれば謄写代 1枚50円と郵送代、振込代金で送ってくることが分かりました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-06-26 11:30／2018/06/06 19:57 URL： https://twitter.com/kk_hirono/status/1276341975524847616 https://twitter.com/hirono_hideki/status/1004316229127950336  

> 大量「懲戒請求」で弁護士会にジレンマ、数百万円の郵送費と「弁護士自治」の間で | ORICON NEWS https://t.co/Nvp8xUUEU6  

 - » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「大量「懲戒請求」で弁護士会にジレンマ」の検索結果 - Twilog https://t.co/lv1iXcdhvy

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-06-26 11:31／2018/06/06 00:30 URL： https://twitter.com/kk_hirono/status/1276342240047058945 https://twitter.com/hirono_hideki/status/1004022779396571136  

> 「オウム事件真相究明の会」立ち上げ記者会見まとめ - Togetter https://t.co/zfO9VLLzpL ■呼びかけ人 青木理（ジャーナリスト） 雨宮処凛（作家） 大谷昭宏（ジャーナリスト） 香山リカ（精神科医、評論家）  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-06-26 11:32／2018/06/05 21:24 URL： https://twitter.com/kk_hirono/status/1276342516799832064 https://twitter.com/shima_chikara/status/1003975928752451585  

> 私にも来ました。懲戒理由は、品位を欠く訴訟宣言（示されたtweetは提訴した他の弁護士の裁判へのコメントなので事実誤認ですが）、和解金の不当請求（猪野弁護士のtweetを引用）、カンパを集める（恐ろしいビジネスモデルと橋下弁護士の… https://t.co/z9W7T4wK9F  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-06-26 11:32／2018/06/05 21:16 URL： https://twitter.com/kk_hirono/status/1276342543727226881 https://twitter.com/ssk_ryo/status/1003973958914355200  

> また、変な懲戒請求が来た。 ・懲戒請求者を挑発した ・カンパを集めた ・賠償請求をしようとしている が、懲戒理由だそうです。アホらしいですが、対応いたします。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-06-26 11:33／2018/06/06 01:52 URL： https://twitter.com/kk_hirono/status/1276342733053911041 https://twitter.com/hirono_hideki/status/1004043412570398720  

> 釜石大観音 - YouTube https://t.co/1qO34keqeu  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-06-26 11:33／2018/06/06 01:55 URL： https://twitter.com/kk_hirono/status/1276342779090620417 https://twitter.com/hirono_hideki/status/1004044107960840192  

> 【ユートピア加賀の郷】 加賀大観音を見てきた 【観音院 加賀寺】 - YouTube https://t.co/QWfyyoqNq6  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-06-26 11:33／2018/06/06 02:10 URL： https://twitter.com/kk_hirono/status/1276342890143182849 https://twitter.com/hirono_hideki/status/1004047738726539264  

> 撮影　2015/9/13 JR加賀温泉駅近くの高台にそびえ立つ巨大な金ピカの観音様 高さは73ｍを誇り、建立当時は日本一の高さだったらしい https://t.co/QWfyyoqNq6  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-06-26 11:34／2018/06/06 02:10 URL： https://twitter.com/kk_hirono/status/1276343032179089408 https://twitter.com/hirono_hideki/status/1004047932360830977  

> かつて「ユートピア加賀の郷」というこの観音様を中心としたテーマパークがありましたが、バブルの崩壊により業績は悪化 遊園地や温泉ホテルは廃業し、現在は寺院部分のみが細々と運営されている状況です その廃れっぷりから地元では「観音様はも… https://t.co/r0EJWGwQza  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-06-26 11:34／2018/06/06 02:13 URL： https://twitter.com/kk_hirono/status/1276343086260445184 https://twitter.com/hirono_hideki/status/1004048630666260486  

> 釜石大観音｜釜石市 - YouTube https://t.co/webeVPlyxS  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-06-26 11:35／2018/06/06 16:47 URL： https://twitter.com/kk_hirono/status/1276343286882463746 https://twitter.com/hirono_hideki/status/1004268602466316290  

> 落合洋司 Yoji Ochiaiさんのツイート: "平成は日本の崩壊の準備期間、次の時代は本格的な崩壊だろう。今、起きていることは、崩壊への前奏曲のようなもの。崩壊の幕が開く。" https://t.co/B9ke2VGUuG  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-06-26 11:37／2018/06/06 19:56 URL： https://twitter.com/kk_hirono/status/1276343780082200577 https://twitter.com/hirono_hideki/status/1004316071464087552  

> なぜ法律デマは出回るのか　約13万件、弁護士への組織的な「懲戒請求」を考える | ORICON NEWS https://t.co/1GEaepwxj1  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-06-26 11:37／2018/06/06 19:58 URL： https://twitter.com/kk_hirono/status/1276343920855638016 https://twitter.com/hirono_hideki/status/1004316526181171200  

> 日弁連「委任状改変」疑惑の顛末…「超アナログ」事務作業で起きた「恥ずかしいミス」 | ORICON NEWS https://t.co/462YQwPMN9 問題を指摘したのは、北周士弁護士(東京弁護士会)だ。北弁護士は、総会のメ… https://t.co/uWQPChSOPk  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-06-26 11:38／2018/06/06 19:58 URL： https://twitter.com/kk_hirono/status/1276343984521007104 https://twitter.com/hirono_hideki/status/1004316679638257670  

> ユッケ食中毒、元社長ら個人への請求棄却、遺族「残念で仕方ない」…運営会社へは賠償命令 | ORICON NEWS https://t.co/ryMKQsRr5c  

　「なぜ法律デマは出回るのか　約13万件、弁護士への組織的な「懲戒請求」を考える」という記事がリンク切れとなっていました。ジャーナリストの江川紹子氏の記事かとも思ったのですが，たぶん違うようなサイトでした。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-06-26 11:42／2013/06/18 09:03 URL： https://twitter.com/kk_hirono/status/1276345009252364288 https://twitter.com/hirono_hideki/status/346780214325563392  

> 検察が弁護士を懲戒請求までして、国民に見せたくなかったものは何か…　→【裁判記録は誰のものか】「これは国民の知る権利の問題です」(江川 紹子) - Y!ニュース ／ジャーナリスト江川紹子 http://t.co/1zQAYVeyoj  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-06-26 11:42／2019/01/01 16:21 URL： https://twitter.com/kk_hirono/status/1276345121764564992 https://twitter.com/hirono_hideki/status/1080001032124395521  

> 5410： ＃　「歪んだ正義感はなぜ生まれたのか…弁護士への大量懲戒請求にみる“カルト性”」というジャーナリストの江川紹子氏のネット記事 https://t.co/EteUcKeidE  

　「なぜ法律デマは出回るのか　約13万件、弁護士への組織的な「懲戒請求」を考える」という記事がリンク切れとなっていました。ジャーナリストの江川紹子氏の記事かとも思ったのですが，たぶん違うようなサイトでした。

 - » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「江川紹子 懲戒」の検索結果 - Twilog https://t.co/dfYOcc6Kby

 - » 歪んだ正義感はなぜ生まれたのか…弁護士への大量懲戒請求にみる“カルト性” https://t.co/TSnEHF9bAQ

　上記のジャーナリストの江川紹子氏の弁護士大量懲戒請求に関する記事は，2018年5月30日となっています。2年ほど前です。記事の読み返しはしないですが，一方的に弁護士らを擁護するような記事で，原因の背景を掘り下げることもなく，表面を都合に合わせなぞったような印象でした。

　録画されたものをYouTubeで視聴したのですが，モーニングショーでも弁護士への大量懲戒請求問題を取り上げ，玉川徹というコメンテーターが，呆れたように笑いながら弁護士は100件ほど案件を抱えている，などと発言していたのが極めて印象的でした。

　すべての視聴は出来なかったのですが，1時間ぐらいは弁護士への大量懲戒請求問題を特集していました。佐々木亮弁護士らの問題性は不問のまま，情報を垂れ流していたのが印象的でした。

 - » 大量　懲戒請求　モーニングショー - YouTube https://t.co/sIZzeMhVqe

　YouTubeの動画は見当たらなくなっていました。動画の場合は，テキストのように引用や転載というのもないので，削除されてしまえば，あとかたもなく消えてしまうという感じです。

 - » ネット住民から 大量懲戒請求 弁護士“反撃”提訴へ/ネット住民 960人に賠償請求へ 軽い気持ち命取り | 羽鳥慎一モーニングショー 2018/05/17(木)08:00のニュース | TVでた蔵… https://t.co/iscShpP9ab

　弁護士らの提訴と，その後，弁護士側の勝訴が続いたという話もありましたが，それをテレビの報道でみることはなく，ネットのニュース記事でも見ていないと思います。昨年の年末から今年の初めにかけての嶋﨑量弁護士のツイートで見かけたという記憶です。

　そして今年の初めには，弁護士大量懲戒請求の民事裁判の取材をしていた女性記者が自殺したというニュースがありました。フリーランスになるのかと思いますが，三宅雪子さんでした。下の方の名前を思い出すのに時間がかかりました。

　今でも，落合洋司弁護士（東京弁護士会）のTwitterアカウントを開くと，「おすすめユーザー」に出えてくることが多いTwitterアカウントです。

 - (1) 弁護士落合洋司🌸高輪ゲートウェイ駅徒歩5分🌸泉岳寺駅徒歩1分（@yjochi）さんの返信があるツイート / Twitter https://twitter.com/yjochi/with_replies  

　10回ほどページの再読込を行いましたが，今回は，三宅雪子さんのTwitterアカウントが「おすすめユーザー」に出てきませんでした。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜miyake_yukiko35（みやけ雪子（世の中を変えるために声をあげよう）） 日時：2020-06-26 12:30／2019/12/30 22:13 URL： https://twitter.com/kk_hirono/status/1276357207534104576 https://twitter.com/miyake_yukiko35/status/1211636517325570048  

> @shima_chikara 年末。少しまじめに手紙を書きました。筆不精な私としては珍しいこと。  

　上記が三宅雪子氏の生前最後のツイートですが，メンションが入っているのが嶋﨑量弁護士のTwitterアカウントになります。返信やコメント付きリツイートにはなっておらず，ユーザ名のメンションだけが入っています。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜miyake_yukiko35（みやけ雪子（世の中を変えるために声をあげよう）） 日時：2020-06-26 12:35／2019/12/30 21:49 URL： https://twitter.com/kk_hirono/status/1276358339589332992 https://twitter.com/miyake_yukiko35/status/1211630340415967235  

> @todateyoshiyuki 先生！一般市民がツイッターは99％です。お、教えてください。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜todateyoshiyuki（戸舘圭之/弁護士/袴田事件弁護団） 日時：2020-06-26 12:35／2019/12/30 21:23 URL： https://twitter.com/kk_hirono/status/1276358352105115648 https://twitter.com/todateyoshiyuki/status/1211623759028731905  

> 勾留理由開示は今の１００倍くらい件数あってもいいと本気と書いてマジで思ってます。  

　今初めて気がついたように思ったのですが，三宅雪子氏の生前，最後の前のツイートが，戸舘圭之弁護士のツイートに対する返信ツイートとなっていました。最後のツイートが2019年12月30日午後10時13分，その1つ前のツイートが午後9時49分となっていました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜todateyoshiyuki（戸舘圭之/弁護士/袴田事件弁護団） 日時：2020-06-26 12:39／2019/12/30 22:11 URL： https://twitter.com/kk_hirono/status/1276359349426810880 https://twitter.com/todateyoshiyuki/status/1211635958509998084  

> @miyake_yukiko35 勾留理由開示って被疑者を勾留する場合に請求があれば公開の法廷で裁判官が理由を言わなければならないと憲法で定めているんですが、めったに利用されていないんです。年間5、600件くらいです。勾留件数は年間その100倍以上はあるんです。  

　戸舘圭之弁護士も午後10時11分に三宅雪子氏に返信を返されていたようです。三宅雪子氏の再度の返信はなく，午後10時13分に，嶋﨑量弁護士のメンションをつけた生前最後のツイートを投稿されています。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜miyake_yukiko35（みやけ雪子（世の中を変えるために声をあげよう）） 日時：2020-06-26 12:49／2019/12/30 11:44 URL： https://twitter.com/kk_hirono/status/1276361939585691649 https://twitter.com/miyake_yukiko35/status/1211478033455968258  

> 北さんには、感謝です。佐々木さんは強い人です。しかし、北さんや労働弁護団がいなかったら、どうだったか。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜miyake_yukiko35（みやけ雪子（世の中を変えるために声をあげよう）） 日時：2020-06-26 12:51／2019/12/30 11:23 URL： https://twitter.com/kk_hirono/status/1276362376015577089 https://twitter.com/miyake_yukiko35/status/1211472735563444225  

> 新しい年に社会的に意義があることをして欲しい。懲戒請求事件。正直にいうとつらかったです。取り上げられた連載は延長になりました。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜miyake_yukiko35（みやけ雪子（世の中を変えるために声をあげよう）） 日時：2020-06-26 12:51／2019/12/30 11:26 URL： https://twitter.com/kk_hirono/status/1276362385217843200 https://twitter.com/miyake_yukiko35/status/1211473635489136640  

> 今年後半は労働問題。労働弁護団、労働弁護士の方の裁判を取り上げました。佐々木さん、尊敬しています。棗さん。棗さんにインタビューできなかったのが残念。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜miyake_yukiko35（みやけ雪子（世の中を変えるために声をあげよう）） 日時：2020-06-26 12:54／2019/12/27 14:29 URL： https://twitter.com/kk_hirono/status/1276363293301469184 https://twitter.com/miyake_yukiko35/status/1210432506110996480  

> 横浜にて。弁護士への大量懲戒請求事件。本日12月27日の裁判と判決について嶋崎量弁護士にインタビュー。 https://t.co/kY6oWVdZH5  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜miyake_yukiko35（みやけ雪子（世の中を変えるために声をあげよう）） 日時：2020-06-26 12:55／2019/12/28 10:38 URL： https://twitter.com/kk_hirono/status/1276363468652732416 https://twitter.com/miyake_yukiko35/status/1210736701968044032  

> 1年振り返って。懲戒請求事件の8回のゲンダイの連載が16回に。体調が悪かった私を気遣ってYさんが｢どうする？｣ と訊いてきました。あと8回は書き下ろし。大変だと思いました。佐々木・北弁護士、金さんら、神原さんの顔が浮かびました。弁… https://t.co/yFFGF8Wx91  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜miyake_yukiko35（みやけ雪子（世の中を変えるために声をあげよう）） 日時：2020-06-26 12:59／2019/12/27 12:16 URL： https://twitter.com/kk_hirono/status/1276364449469755398 https://twitter.com/miyake_yukiko35/status/1210398936285900802  

> 横浜地裁。今日は嶋崎(スマホ変換できず)弁護士被告原告裁判。判決もあります。３件。私は11時原告裁判から。傍聴人多し。たぶん多くはブログ主側。嶋崎弁護士側は代理人のみ。現在、嶋崎弁護士事務所。11時終了後、懲戒請求者側代理人の徳永… https://t.co/AeTXBtlcsn  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜miyake_yukiko35（みやけ雪子（世の中を変えるために声をあげよう）） 日時：2020-06-26 12:59／2019/12/27 15:07 URL： https://twitter.com/kk_hirono/status/1276364461238923264 https://twitter.com/miyake_yukiko35/status/1210442139127037952  

> 来年2020年懲戒請求者側代理人の徳永弁護士(ら)のお話も詳しく伺います。無我夢中の１年でした。ありがとうございました。  

　タイムラインを遡り探していたのは，上記2件のツイートで，徳永弁護士の名前があります。

**** 「大量懲戒請求に対する損害賠償が不当な理由　3億円の正体（カラクリ）」という猪野亨弁護士（札幌弁護士会）のブログ記事

　本当は，2019年12月27日の故三宅雪子氏のツイートにあった徳永弁護士の記事を探したのですが，ほとんどYouTubeの動画しか情報がありませんでした。そのYouTubeの動画で徳永弁護士との対談もみている，猪野亨弁護士の記事ですが，これは前にも読んでいるものです。

　以前，猪野亨弁護士と大阪の徳永信一弁護士との対談のYouTube動画で視聴したのと同様の内容が，この猪野亨弁護士のブログ記事にはテキストとして情報が記されています。

```
ところで世間では、懲戒請求を「大量」にされたら大きな労力、負担になっているんではないかという誤解が蔓延しています。これは由々しきものです。
　当初はマスコミもセンセーショナルに報じました。だから事務負担など業務に影響が出るくらいのことになっているのではないか、そんな印象を持ちませんでしたか。

　それ自体も間違いだし、そもそも原告らが請求する額が非常識なのです。
　北海道訴訟では、原告らは、予備的請求ですが、一人に対して50万円の損害賠償請求を行っています。道内52人に対しては合計で2600万円となります。
　全国では960人からの請求ですから、その全体の額は4億8000万円にもなります。
　いくら大量懲戒請求とはいえ、本当にこれだけの精神的苦痛を負ったのでしょうか。この額は近親者が20名近く一度に死亡したときの慰謝料額に匹敵するものです。
　これだけみても非常識な請求であり、弁護士としての品位を欠くと言わざるを得ません。

［source：］大量懲戒請求に対する損害賠償が不当な理由　3億円の正体（カラクリ） - 弁護士 猪野 亨のブログ http://inotoru.blog.fc2.com/blog-entry-4295.html
```

　「何故、その程度の負担しかないのに、世間は対象となった弁護士が大変なことになっていると多くの人たちが誤解したのかといえば、最初に記者会見した佐々木亮、北周士弁護士らが極めて大げさ、誇張してマスコミ発表をしたからということと、それをさらに煽るようにマスコミが報道したからです。」

　「当たり前のことです。1人30万円であれば全体で3億円。50万円であれば5億円にもなってしまうのですが、これがあまりに常識を逸することは誰がみてもわかります。」

　上記2点の「」書きも，猪野亨弁護士のブログ記事の引用になります。よく見ると，記事の日付が2019年12月26日10時05分となっています。故三宅雪子さんもこの記事を読んでいたのかもしれません。

　さきほど徳永信一弁護士をGoogleで調べていたところ，「余命三年時事日記」の執筆者で弁護士大量懲戒請求問題の扇動者とされた人物の実名と顔写真の記事が見つかりました。たぶん初めて見るような名前でしたが，何故今ごろに名前が出ているのかという不思議さがあります。

　嶋﨑量弁護士，佐々木亮弁護士，北周士弁護士らもなぜかこの「余命三年時事日記」の執筆者で弁護士大量懲戒請求問題の扇動者とされた人物の責任を追求するのではなく，扇動された同調者に一人頭は多くないですが，総額で3億円とも5億円ともされる賠償裁判を始めたようです。

　猪野亨弁護士のブログですが，ブログの存在はかなり前から知っていて，同調できない内容の記事ばかりという印象があったのですが，この「大量懲戒請求に対する損害賠償が不当な理由　3億円の正体（カラクリ）」ついては，とてもわかり易く合理的な説明だと理解していました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-06-26 13:41／2012/01/06 13:39 URL： https://twitter.com/kk_hirono/status/1276374954091491328 https://twitter.com/hirono_hideki/status/155146457756864513  

> 給与制廃止はなんとか1年伸びましたが、マスコミは合格者数削減、給与制廃止反対は「業界の既得権益の確保だ」とばかり、一様に批判的です。しかしこれは全く物事の本質を見ていないとしか言いようがありません。 猪野亨弁護士が、そういう朝日新聞の社説 http://t.co/KBukbJKT  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-06-26 13:41／2013/09/01 22:11 URL： https://twitter.com/kk_hirono/status/1276375028846624768 https://twitter.com/hirono_hideki/status/374157482857603072  

> 弁護士　猪野亨のブログ http://t.co/qq4YjvgOyC  

 - » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「猪野亨」の検索結果 - Twilog https://t.co/QZgG24stUk

　Twilogで確認しましたが，思っていたより時期は早く，2012年1月6日に猪野亨弁護士の名前のあるツイートがあって，2013年9月1日にはブログの存在を知っていたようです。

　猪野亨弁護士のブログは裁判員制度に批判的なものがあったように記憶をしていますが，そういえばけっこう長い間，名前を見かけずにいました。ほとんどがブログ記事の紹介でしたが，Twitterのアカウントもあったはずです。

 - » 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中: REGEXP：”猪野亨（弁護士）？”／データベース登録済みツイート：2020年01月07日22時25分の記録：ユーザ・投稿：15／51件 https://t.co/g6QgMrlXbU

　また，気になる小倉秀夫弁護士のツイートをまとめ記事で見つけました。

**** 「余命三年時事日記の呼びかけに応じて「日本人対在日朝鮮人」の闘いの一環として弁護士どもに大量に懲戒請求をした愛国者様たちに責任を」という小倉秀夫弁護士のツイート

 - 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中: REGEXP：”（猪野亨（弁護士）？｜猪野弁護士）”／データベース登録済みツイート：2020年06月26日13時59分の記録：ユーザ・投稿：19／87件 http://hirono2014sk.blogspot.com/2020/06/regexp2020062613591987.html#p43

 - （43／87） TW Hideo_Ogura（小倉秀夫） 日時： 2018-07-05 08:06:00 +0900 URL： https://twitter.com/Hideo_Ogura/status/1014646572192153600

> 余命三年時事日記の呼びかけに応じて「日本人対在日朝鮮人」の闘いの一環として弁護士どもに大量に懲戒請求をした愛国者様たちに責任をとらせようとする弁護士を、札幌の猪野弁護士はどうしてそこまで攻撃するんでしょうね。

　「「日本人対在日朝鮮人」の闘い」を扇動し，利用しているように思える弁護士が少なくないのですが，小倉秀夫弁護士のツイートは最もストレートでわかりやすくなっているように思われます。

　よくみると上記の小倉秀夫弁護士のツイートは投稿が2018年7月5日となっていて，2019年12月26日の猪野亨弁護士のブログ記事とはずいぶん間があります。

　そういえば今日，小倉秀夫弁護士のプロフィールに法律事務所のパートナー弁護士となっていることを発見しました。よく見た名前の法律事務所で，以前Googleマップで調べたところ，最高裁判所の近くに事務所がありました。

```
経歴
1991　司法試験合格
1992　早稲田大学法学部卒業
1994　司法修習終了（46期）
1994　弁護士登録（東京弁護士会）
2000　中央大学法学部兼任講師
2001　当法律事務所パートナー
知的所有権研究会事務局長
民事訴訟法学会、情報ネットワーク法学会会員

［source：］小倉　秀夫｜スタッフ紹介｜事務所紹介｜東京平河法律事務所 http://www.tokyo-hirakawa.gr.jp/office/lawyer/staff19.html
```

　「2001　当法律事務所パートナー」とあります。内容に変更があった可能性はあると思いますが，変わりがないのであれば，気にすることなく読み飛ばし頭に入らない情報になっていたようです。

　1994年というのは平成6年ですが，平成13年に当法律事務所パートナーになる間の弁護士活動が記載されていないように読めます。中央大学法学部兼任講師というのも平成12年のこととなっています。

**** 独自の強いこだわりをみせた「女性専用車両」をキーワードに含む小倉秀夫弁護士の836件のツイートの記録

➜  ~ ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb Hideo_Ogura '女性専用車両' '1000-01-01/3000-01-01'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1000-01-01' AND '3000-01-01' AND (user LIKE "Hideo_Ogura") AND  tweet REGEXP "女性専用車両"  ORDER BY tw_date ASC
REGEXP：”女性専用車両”／小倉秀夫（@Hideo_Ogura）の検索（2011-11-19〜2019-06-02／2020年06月26日15時04分の記録836件）

 - 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中: REGEXP：”女性専用車両”／小倉秀夫（@Hideo_Ogura）の検索（2011-11-19〜2019-06-02／2020年06月26日15時04分の記録836件） http://hirono2014sk.blogspot.com/2020/06/regexphideoogura2011-11-192019-06.html#p793

  - （793／836） TW Hideo_Ogura（小倉秀夫） 日時： 2018-07-31 08:43:00 +0900 URL： https://twitter.com/Hideo_Ogura/status/1024077940311580673

> 特定の犯罪の被害に遭う不利益と特定の場から排除される不利益とを比較し、犯罪被害に遭う不利益の方が大きいから特定の場から排除されるのは甘受せよという話じゃないですか、女性専用車両も女性専用国家も。RT @bonyouben: 裸の利益衡量は、法的安定性に欠けるのでやめましょう

 - （794／836） TW Hideo_Ogura（小倉秀夫） 日時： 2018-07-31 08:46:00 +0900 URL： https://twitter.com/Hideo_Ogura/status/1024078931295580160

> 「男性による犯罪を日本の女性に甘受せよというのか！」という批判を前に、日本を女性専用国家にしようという見解に対する批判は敗れ去るんじゃないですか。女性専用車両肯定論の論理を受け容れたら。RT @bonyouben:

　小倉秀夫弁護士に関しては，一時テレビでも取り上げられていたブラックボックスの問題で，被害者側の代理人をやっているような情報を見かけたことがありました。刑事事件としては犯罪の証明が絶望的というような解説をみた問題でもありました。

 - » 小倉秀夫弁護士　ブラックボックス - Google 検索 https://t.co/XZAF3uk1bv

　検索結果に伊藤詩織さんの名前あ出てきて，少ししてから思い出したのですが，伊藤詩織さんの出した本のタイトルも「ブラックボックス」になっていたことを思い出しました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-06-26 15:30／2017/12/29 21:41 URL： https://twitter.com/kk_hirono/status/1276402392594931712 https://twitter.com/hirono_hideki/status/946722783681286144  

> 「ブラックボックス展で痴漢されPTSDに」主催者らに損害賠償求め、女子大生が提訴 https://t.co/jQuP3lNPvR  

　検索結果に伊藤詩織さんの名前あ出てきて，少ししてから思い出したのですが，伊藤詩織さんの出した本のタイトルも「ブラックボックス」になっていたことを思い出しました。

 - » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「ブラックボックス」の検索結果 - Twilog https://t.co/1DiUxUjR78

　Googleの検索では手がかりさえ見つからず，「ブラックボックス」という言葉に少し思い違いがあるのかと考え始めていたのですが，Twilogで情報を見つかることが出来ました。「ブラックボックス展」となっています。

```
女子大生はこの呼びかけを見て、代理人の小倉秀夫弁護士を通じて主催者側に連絡をとった。しかし、主催者「なかのひとよ」氏からは何の返事もなかった。

さらに、ギャラリーの責任者とみられる人物は、小倉弁護士と電話で会話中に「こちらから（女性を）訴える」といった趣旨の話をしたという。

女子大生は「主催者らは、世間に向けたインタビューなどでは『反省している』などと語っているが、その裏で、実際には被害者に対して何の責任も取ろうとしていない」と憤りを語った。

「主催者とギャラリーは、言っていることと裏でやっていることが違う。それを知ってほしかった」という思いが、提訴まで至った背景の一つにあるという。

［source：］「ブラックボックス展で痴漢されPTSDに」主催者らに損害賠償求め、女子大生が提訴 | ハフポスト https://www.huffingtonpost.jp/2017/12/28/black-box_a_23319139/
```

　記事に小倉秀夫弁護士の名前が出ています。上記の引用部分にはないですが，「痴漢被害に遭ったと訴える女子大学生（22）が、展覧会の主催者とギャラリーを相手取って、約1100万円の損害賠償を求める裁判を東京地裁に起こした。提訴は12月27日付。」とあります。

　損害賠償の民事裁判を提訴した後の情報はほとんど見つかりませんでした。痴漢というのは通常，個人の犯罪であったり，民法上は不法行為になるのだと思いますが，主催者の管理に落ち度があるとして約1100万円という賠償請求になったのでしょう。強姦でも1千万円の請求は聞かない気がします。

 - （797／836） TW Hideo_Ogura（小倉秀夫） 日時： 2018-07-31 09:09:00 +0900 URL： https://twitter.com/Hideo_Ogura/status/1024084572726734848

> 女性専用車両の論理からすれば、「男性が大学に通うことを禁止」することも容易に導けますし。確かに、高卒でも働けますから。RT @bonyouben: @Hideo_Ogura 私は、そのようには考えていません。 https://t.co/D2lsas0pax

 - （801／836） TW Hideo_Ogura（小倉秀夫） 日時： 2018-09-20 09:54:00 +0900 URL： https://twitter.com/Hideo_Ogura/status/1042577745660657664

> 女性専用車両が定着すれば、最終的には女性専用国家に行き着くわけで。RT @bonyouben: 大丈夫。
> 「日本人男性の分際で、日本人女性が存在する場所に立ち入っても構わないとされている」という社会構造(？)は、誰も問題にしてないですよ。
> 大丈夫です。

 - （811／836） TW Hideo_Ogura（小倉秀夫） 日時： 2018-11-12 01:41:00 +0900 URL： https://twitter.com/Hideo_Ogura/status/1061660076383993856

> ええ。黒人の中にそういう人がいたからって黒人を一律に排除すれば黒人差別となるのと同様に。RT @aomathuri: 通報した。こういう奴が日本男性に混ざってるんなんて怖すぎる･･･これでも女性専用車両は差別と言えるのか？？？ https://t.co/scC0oKYnuK

　痴漢防止目的の女性専用車両を差別と決めつけ，世界的，歴史的な黒人差別の問題と抱き合わせにするというのは，飛躍を感じますし，それも弁護士の立場でツイートをしているわけです。この差別は弁護士が差別を扇動，悪用していることの証左に他ならない事例かと思います。

 - （816／836） TW Hideo_Ogura（小倉秀夫） 日時： 2019-05-28 08:04:00 +0900 URL： https://twitter.com/Hideo_Ogura/status/1133146942014275585

> 「女性専用車両」という、「男は皆犯罪者予備軍だから隔離」として女性の虚栄心を刺激する解決策がとられ始めた以上、男性の人権をより損なわない手法など歓迎されるはずがない。高校／大学の始業時間の調整とか、男性を二級市民として貶めるものにならないからね。

 - （819／836） TW Hideo_Ogura（小倉秀夫） 日時： 2019-05-28 08:21:00 +0900 URL： https://twitter.com/Hideo_Ogura/status/1133151317357031425

> 普通に男性差別ですね。RT @nekoya_2222: 痴漢の多さや卑劣な事件から作られた女性専用車両というシェルターを、本気で男性差別だと思っている人がそれなりにいることが恐ろしいよな

 - （826／836） TW Hideo_Ogura（小倉秀夫） 日時： 2019-05-28 09:33:00 +0900 URL： https://twitter.com/Hideo_Ogura/status/1133169371847651328

> 女性専用車両推進論者の本音は「男性が居なくなれば」ということなんでしょうね。RT @Elice_13: @Hideo_Ogura @bonmoment39 黒人が居なくなれば…って事を暗に言いたい訳か…

　こういうツイートをしていても，弁護士としての職業，生活には余り影響がないのでしょう。そればかりか，感覚を狂わせ，判断を鈍らせて金銭を巻き上げるのが弁護士商売の伝統芸や秘訣にしているのかとも思えてきます。

 - （830／836） TW Hideo_Ogura（小倉秀夫） 日時： 2019-05-28 22:59:00 +0900 URL： https://twitter.com/Hideo_Ogura/status/1133372345756684291

> 女性専用車両のような荒っぽい隔離政策に賛同できるのって、自分たちは、自分たちと異なる属性集団を隔離する側、つまりマジョリティの側にいるという自覚が、女性の側にあるからだよね。

 - （836／836） TW Hideo_Ogura（小倉秀夫） 日時： 2019-06-02 11:58:00 +0900 URL： https://twitter.com/Hideo_Ogura/status/1135017815990161409

> 一部の鉄道会社が「女性専用車両」なるものを設定して、男性を一律に性犯罪予備軍と規定して特定の公的スペースの利用を排除しています。RT @Kino_Eesti:「男性差別」って例えば具体的に何ですか？ https://t.co/vhZ3ELAZA8

　小倉秀夫弁護士のTwitterアカウントは，次のリツイートを最後に停止しています。当時の小倉秀夫弁護士のTwitterとは別の発言によれば，Twitter社から新規投稿ができない凍結を受けたようです。指摘されたツイートを削除すれば，すぐに復活したような感じでありました。

RT Hideo_Ogura（小倉秀夫）｜Yukishige190102（かになべ(抑える@自戒)） 日時：2019-06-08 07:09／2019-06-07 23:53 URL： https://twitter.com/Hideo_Ogura/status/1137119368846798848 https://twitter.com/Yukishige190102/status/1137009600782192640
> [名古屋地裁岡崎支部平成31年3月26日準強制性交罪無罪判決、分析してみました。] https://t.co/3tElQHuCze \n  \n 読むのは大変辛いけれども \n 裁判とは、かくも理性的でなくてはならぬと同時に \n 理性的すぎる事は実に気… https://t.co/o2hPnQQSM6


